# -*- org -*-
# -*- coding:utf-8 -*-

# Time-stamp: <2016-07-23 16:39:36 (mykulou@gmail.com)>
#+SETUPFILE: theme-bigblow-local.setup
#+TITLE: 电影和小说

* 好电影，好动画 
  - [[http:zh.wikipedia.org/wiki/%E5%8B%95%E7%95%AB%E9%9B%BB%E5%BD%B1][来源维基]]
** 已看过：
   - 十二怒汉、美国往事、罗马假日、楚门的世界、指环王、七宗罪、黑客帝国、浪潮（5天极权）、沉默的羔羊（汉尼拔）、阿甘正传、
   - 美丽人生（早上好，我美丽的公主）、肖申克的救赎、辛德勒的名单
   - 星球大战
*** 数学相关：
    - 美丽心灵、极限空间（数学家、密室）
*** 中国：
    - 霸王别姬、无间道、大闹天宫
*** 日本：
    - 七武士、入殓师、
    - 风之谷、天空之城、龙猫、幽灵公主、千与千寻、悬崖上的金鱼公主、侧耳倾听、
    - 秒速五厘米、云之彼端约定地方、追逐繁星的孩子、星之声、
    - 萤火之森、穿越时空的少女、 壳中少女、钢琴之森、空中杀手、意外的幸运签、 空之境界、恶童、 你看起来好像很好吃、大都会、

*** 还不错：
    - 上帝之城
*** 未看：
    - 东京物语、博士热爱的算式
    - 一一
    - 西西里的美丽传说、穆赫兰道、维罗尼卡的双重生命、搏击俱乐部
    - 乱世佳人、泰坦尼克、飞越疯人院、 钢琴家
    - 星际旅行系列
    - 飞屋环游记、  狮子王、萤火虫之墓、哈尔的移动城堡、 红猪、未麻之部屋、河童之夏、千年女优、狼的孩子雨和雪、*攻壳机动队*

** 动画：
   - 银魂、钢之炼金术、黑之契约者、死亡笔记   

* 电影史上最伟大的10部电影（全球顶尖影评人权威评选）
  - 已看过：教父、七武士
    未看：
** 最伟大导演
   - 他们是茂瑙，让维果，戈达尔，卓别林，奥森・威尔斯，希区柯克，乔治
     库克，法斯宾德， 塔可夫斯基，费里尼，安东尼奥尼，库布里克，伯格曼。
     
** 视与听 榜单
   - 1952 年，世界上颇具影响力的英国电影评论期刊《视与听》(Sight &
     Sound)招集了当时全球最顶尖的几百位影评人，让他们评选自己心目中
     “电影史上最伟大的10部电影”，此后这项传统一直延续了下来，每10年
     重新评选 一次，每次都成为电影界的盛世。最近一次评选为2002年（从92
     年开始又开设了导演评选），回顾这8次名单（6次影评人评选，2次导演评
     选），我们从中 可以看出，哪些影片是能够经受住历史的检验而屹立不倒
     的真正的经典。
     
   - 综合这8张榜单，迄今为之上榜2次以上的电影共有21部，按着上榜次数、
     名次等多方面考虑，这21部电影的最终排名如下，它们代表着世界电影艺
     术的最高成就：
*** 多次上榜
    - 上榜7次：
      1、公民凯恩Citizen Kane 1941 美国
          导演：奥逊?威尔斯
      2、游戏规则The Rules of the Game 1939 法国
          导演：让?雷诺阿
    
    - 上榜6次：
      3、战舰波将金号The Battleship Potemkin 1925 苏联
          导演：谢尔盖?爱森斯坦
    
    - 上榜5次：
      4、八部半 1963 意大利、法国
          导演：费德里科?费里尼
      5、迷魂记Vertigo 1958 美国
          导演：阿尔弗雷德?希区柯克
    
    - 上榜4次：
      6、圣女贞德受难记La Passion de Jeanne d' Arc 1928 法国
          导演：卡尔?西奥多?德莱叶
    
    - 上榜3次：
      7、教父1 2 The Godfather 1 2 1972 1974 美国
          导演：弗朗西斯?福特?科波拉
      8、奇遇L'avventura 1960 意大利、法国
          导演：米开朗基罗?安东尼奥尼
      9、偷自行车的人The Bicycle Thief 1948 意大利
          导演：维托里奥?德?西卡
      10、亚特兰大号L'atalante 1934 法国
          导演：让?维果
      11、七武士The Seven Samurai 1954 日本
          导演：黑泽明
    
    - 上榜2次：
      12、东京物语Tokyo Story 1953 日本
          导演：小津安二郎
      13、愤怒的公牛Raging Bull 1980 美国
          导演：马丁?西科塞斯
      14、贪婪Greed 1924 美国
          导演：埃里克?冯?斯特劳亨
      15、雨中曲Singin' in the Rain 1952 美国
          导演：斯坦利?多南、吉恩?凯利
      16、雨月物语Tales Of Ugetsu 1953 日本
          导演：沟口健二
      17、搜索者The Searchers 1956 美国
          导演：约翰?福特
      18、伟大的安伯逊家族 The Magnificent Ambersons 1942 美国
          导演：奥逊?威尔斯
      19、2001太空漫游2001: A Space Odyssey 1968 英国、美国
          导演：斯坦利?库布里克
      20、将军号The General 1926 美国
          导演：克莱德?布鲁克曼、巴斯特?基顿
      21、罗生门Rash?mon 1950 日本
          导演：黑泽明?3title
    
*** 2012年8月公布
    1. 迷魂记 Vertigo
       导演 : Alfred Hitchcock
    2. 公民凯恩 Citizen Kane
       导演 : Orson Welles
    3. 东京物语
       导演 : 小津安二郎
    4. 游戏规则 La règle du jeu
       导演 : Jean Renoir
    5. 日出 Sunrise: A Song of Two Humans
       导演 : F・W・茂瑙 F.W. Murnau
    6. 2001太空漫游 2001: A Space Odyssey
       导演 : Stanley Kubrick
    7. 搜索者 The Searchers
       导演 : John Ford
    8. 持摄影机的人 Человек с киноаппаратом
       导演 : 吉加・维尔托夫 Dziga Vertov
    9. 圣女贞德蒙难记 La passion de Jeanne d'Arc
       导演 : Carl Theodor Dreyer
    10. 八部半 8?
        导演 : Federico Fellini
    
** 《视与听》2012影史二十五大导演排名（864位电影评论家和学者的投票结果）
   一：阿尔弗雷德・希区柯克 Alfred Hitchcock（1899-08-13，1980-04-29）
       318票
   二：让-吕克・戈达尔 Jean-Luc Godard（1930-12-03
       238票
   三：奥森・威尔斯  Orson Welles（1915-05-06，1985-10-10）
       231票
   四：小津安二郎 Yasujiro Ozu（1903-12-12，1963-12-12）
       189票
   五：让・雷诺阿 Jean Renoir（1894-09-15，1979-02-12）
       179票
   六：约翰・福特 John Ford（1894-02-01，1973-08-31）
       158票
   七：卡尔・西奥多・德莱叶 Carl Theodor Dreyer（1889-02-03，1968-03-20）
       158票
   八：斯坦利・库布里克 Stanley Kubrick（1928-07-26，1999-03-07）
       157票
   九：安德烈・塔科夫斯基 Andrei Tarkovsky（1932-04-04，1986-12-29）
       153票
   十：罗伯特・布列松 Robert Bresson（1901-09-25，1999-12-18）
       149票
   11：弗朗西斯・福特・科波拉 Francis Ford Coppola（1939-04-07
       145票
   12：英格玛・伯格曼 Ingmar Bergman（1918-07-14，2007-07-30）
       143票
   13：F・W・茂瑙 F.W. Murnau（1888-12-28，1931-03-11）
       134票
   14：费德里科・费里尼 Federico Fellini（1920-01-20，1993-10-31）
       129票
   15：黑泽明 Akira Kurosawa（1910-03-23，1998-09-06）
       127票
   16：路易斯・布努埃尔 Luis Bunuel（1900-02-22，1983-07-29）
       114票
   17：米开朗基罗・安东尼奥尼 Michelangelo Antonioni（1912-09-29，2007-07-30）
       110票
   18：查理・卓别林 Charles Chaplin（1889-04-16，1977-12-25）
       98票
   19：马丁・斯科塞斯 Martin Scorsese（1942-11-17
       97票
   20：大卫・林奇 David Lynch（1946-01-20
       92票
   21：弗里茨・朗 Fritz Lang（1890-12-05，1976-08-02）
       91票
   22：谢尔盖・爱森斯坦 Sergei M. Eisenstein（1898-01-23，1948-02-11）
       88票
   23：沟口健二 Kenji Mizoguchi（1898-05-16，1956-08-24）
       85票
   24：迈克尔・鲍威尔 Michael Powell，默力・皮斯伯格 Emeric Pressburger
        （1905-09-30，1990-02-19）（1902-12-05，1988-02-05）
       84票
   25：罗伯托・罗西里尼 Roberto Rossellini（1906-05-08，1977-06-03）
       83票 
* 百年百大电影
  -
    [[http://zh.wikipedia.org/wiki/AFI%E7%99%BE%E5%B9%B4%E7%99%BE%E5%A4%A7%E9%9B%BB%E5%BD%B1][
   来源维基]]
** 名单
   - 斯蒂芬・斯皮尔伯格以5片作品（《辛德勒的名单》、《E.T.》、《大白
     鲨》、《夺宝奇兵》、《拯救大兵瑞恩》），成为出现次数最多的导演。
     阿尔弗雷德・希区柯克、斯坦利・库布里克、比利・怀德各以4片居次。法
     兰克・卡普拉、查理・卓别林、弗朗西斯・科波拉、约翰・休斯顿、马丁・
     西科塞斯各以3片居第三。
     
   - 詹姆斯・史都华是惟一一位主演电影最多的演员，计5部作品（《迷魂记》、
     《风云人物》、《史密斯游美京》、《费城故事》、《后窗》）。罗伯特・
     德尼罗出现在5部电影，不过在4部电影（《愤怒的公牛》、《出租车司机》、
     《猎鹿人》、《盗亦有道》）是主角，1部电影（《教父2》）是配角。劳
     勃・杜瓦一共出现在6部电影（《杀死一只知更鸟》、《外科医生》、《教
     父》、《教父2》、《萤光幕后》、《现代启示录》），但全部都是戏份不
     等的配角。
     
   - 凯瑟琳・赫本（主演《费城故事》、《非洲皇后》（The African Queen）、
     《育婴奇谭》（Bringing Up Baby））、费・唐娜薇（主演《唐人街》、
     《邦尼和克莱德》、《萤光幕后》），各出现在3部电影，并列主演次数最
     多的女演员。黛安・基顿出现在3部电影，在其中1片（《安妮・霍尔》）
     是主角，另外2片（《教父》、《教父2》）是配角。
     
   - 1970年代以20片电影出现次数最多。
     
   - 1969年、1976年、1982年各出现了4片电影，多于其他年份。
     
    - 年代最早的电影是1916年的《忍无可忍》（Intolerance）。最近的是
      2001年的《指环王：护戒使者》。
      
    - 此份名单计有6部默片、2部动画。
      
    - 此份名单计有6部歌舞片、6部西部片、5部科幻片、18部喜剧片。
** 提名名单
   - 阿尔弗雷德・希区柯克及威廉・惠勒各以10片作品，成为出现次数最多的导演。史蒂芬・斯皮尔伯格、霍华德・霍克斯各以8片居次。比利・怀德、乔治・史蒂芬斯各以7片居第三。

   - 詹姆斯・史都华与亨利・方达各以10片作品，成为出现次数最多的演员。卡莱・葛伦以9片作品居次。罗伯特・德尼罗、杰克・尼克尔森以8片居第三。

   - 女演员以凯瑟琳・赫本的7片电影最多。贝蒂・戴维斯、莉莲・吉许各5片居次。

* 电影和小说
** 挪威的森林 (村上春树)
   导演： 陈英雄
   主演： 松山健一 菊地凛子 水原希子
   - 一本青春恋爱小说，这是一部动人心弦的、平缓舒雅的、略带感伤的、百
     分之百的恋爱小说。
** 一个陌生女人的来信 (茨威格)
   导演： 徐静蕾
   主演： 徐静蕾 姜文
   - 讲述的是一个陌生的女人，在她生命的最后时刻，饱蘸着一生的痴情，写
     下了一封凄婉动人的长信，向一位著名的作家袒露了自己绝望的爱慕之情。
     小说以一名女子最痛苦的经历，写出了爱的深沉与奉献。
** 哈利波特 (J.K.罗琳)
   导演： 克里斯・哥伦布
   主演： 丹尼尔・雷德克里夫 鲁伯特・格林特 爱玛・沃森
** 别让我走 (石黑一雄)
   导演： 马克・罗曼尼克
   主演： 凯瑞・穆丽根 凯拉・奈特莉
   - 故事主角三个在寄宿学校一起长大的伙伴，有一天发现自己原来是克隆人，而
     存在的唯一目的就是为别人提供移植的器官……如果我没有选择生死的权
     利，那么至少别让我孤独的过完短暂的一生。
** 倩女幽魂
   导演： 程小东
   主演： 张国荣 王祖贤 午马
** 大话西游
   导演： 刘镇伟
   主演： 周星驰 莫文蔚 吴孟达
** 卧虎藏龙 (王度庐)
   导演： 李安
   主演： 周润发 杨紫琼 章子怡 
** 东邪西毒
   导演： 王家卫
   主演： 张国荣 梁家辉 林青霞 梁朝伟
** 失乐园 (渡边淳一)
   导演： 森田芳光
   主演： 役所广司
   - 追求终极之爱，这是一部梦幻与现实、灵与肉、欢悦与痛楚相互交织的震
     撼心灵的杰作
** 伊豆的舞女 (川端康成)
   导演： 西河克己
   主演： 山口百惠 三浦友和
   - 少男少女之间初恋的那种朦胧、纯真的情感
** 白痴 (陀思妥耶夫斯基)
   导演： 黑泽明
   主演： 原节子 森雅之 三船敏郎
   - 一个纯真无垢的人，卷入充满失望、爱恨的世界中会产生什么样的反应和
     结果
** 香水 (帕特里克・聚斯金德 德国)
   导演： 汤姆・提克威
   主演： 本・威士肖 阿伦・瑞克曼 蕾切儿・哈伍德
   - 从小缺乏爱与被爱的格雷诺耶，自身也没有任何气味，而从那些充满美好
     情致的纯真女子身上，他一定是嗅到了某种令他感到安慰、迷恋、怡人的
     温暖味道。
** 理智与情感 (简・奥斯汀)
   导演： 李安
   主演： 凯特・温丝莱特 休・格兰特
   - 
** 傲慢与偏见 (简・奥斯汀)
   导演： 乔・怀特
   主演： 凯拉・奈特莉 马修・麦克费登 吉娜・马隆
** 英国病人 (迈克尔・翁达杰)
   导演： 安东尼・明格拉
   主演： 拉尔夫・费因斯 克里斯汀・斯科特・托马斯 朱丽叶・比诺什
   - 这是一部史诗般的爱情电影，影片以时空交错和两个爱情故事交叉的蒙太
     奇方式展开。
** 活着 (余华)
   导演： 张艺谋
   主演： 葛优 巩俐
   - 影片露出一股悲悯情怀和伤感的黑色幽默，它将历史浓缩为个人命运，而
     命如蝼蚁般的个人命运，只能是枉自兴叹的生命之痛。
** 洛丽塔 (弗拉基米尔・纳博科夫)
   导演： 斯坦利・库布里克
   主演： 詹姆斯・梅森 谢利・温特斯 苏・莱恩
   - 个中年男子与一个未成年少女的恋爱故事
** 不能承受的生命之轻 (米兰昆德拉)
   导演： 菲利普・考夫曼
   主演： 丹尼尔・戴-刘易斯 朱丽叶・比诺什
   - 他以一个哲人的睿智将人类的生存情景提升到形而上学的高度加以考虑、
     审查和描述；由此成功地把握了政治与性爱两个敏感领域
** 情人 (杜拉斯)
   导演： 让-雅克・阿诺
   主演： 珍・玛奇 梁家辉 让娜・莫罗 
   - 只有一个人，爱你那朝圣者的灵魂，爱你衰老的脸上痛苦的皱纹。
** 杀死一只知更鸟 (哈伯·李)
   导演： 罗伯特・马利根
   主演： 格利高里・派克 玛丽・巴德哈姆 罗伯特・杜瓦尔
   - 自传体小说，也是她的第一本和唯一一本著作
** 西线无战事 (埃里希・马里亚・雷马克)
   导演： 刘易斯・迈尔斯通
   主演： 路易斯・沃海姆 刘・艾尔斯 本・亚历山大
   - 最伟大的反战电影
** 铁皮鼓 (君特·格拉斯 )
   导演： 沃尔克・施隆多夫
   主演： 马里奥・阿多夫 安吉拉・温科勒 大卫・本奈特
   - 最著名的反纳粹电影，荒诞家庭里诞生的荒诞怪小孩用拒绝长大的荒诞手
     法来对抗这个荒诞的世界。
** 日瓦戈医生 (帕斯捷尔纳克)
   导演： 大卫・里恩
   主演： 奥马尔・沙里夫 朱莉・克里斯蒂 杰拉丁・卓别林
   - 大时代动荡背景下的小人物的命运沉浮。在极权之下，高尚的事务显得那么苍白。
** 安娜・卡列尼娜 (托尔斯泰)
   导演： 克拉伦斯・布朗
   主演： 葛丽泰・嘉宝 弗雷德里克・马奇 费雷迪・巴塞洛缪
   - 主人公安娜・卡列尼娜是世界文学史上最优美丰满的女性形象之一。她以
     内心体验的深刻与感情的强烈真挚，以蓬勃的生命力和悲剧性命运而扣人
     心弦。
** 战争与和平 (托尔斯泰)
   导演： 金・维多
   主演： 奥黛丽・赫本 亨利・方达 梅尔・弗尔
   - 《战争与和平》恢弘的构思和卓越的艺术描写震惊世界文坛，成为举世公
     认的世界文学名著和人类宝贵的精神财富。
** 蒂凡尼的早餐 (杜鲁门・卡波特)
   导演： 布莱克・爱德华兹
   主演： 奥黛丽・赫本 乔治・佩帕德 斯坦利・亚当斯
   - 
** 广岛之恋 (玛格丽特・杜拉斯)
   导演： 阿伦・雷乃
   主演： 埃玛妞・丽娃 冈田英次 贝尔纳・弗雷松
   - 《广岛之恋》以其现代意义的题材，暧昧多义的主题，令人震惊的表现手
     法，与新小说派的紧密联结，在多重意义上，启发和开创了现代电影。
** 肖申克的救赎 (斯蒂芬・金)
   导演： 弗兰克・德拉邦特
   主演： 蒂姆・罗宾斯 摩根・弗里曼
*** 闪灵 (斯蒂芬・金)
    导演： 斯坦利・库布里克
    主演： 杰克・尼科尔森
** 魔戒 (约翰・罗纳德・鲁埃尔・托尔金)
   导演： 彼得・杰克逊
   主演： 伊安・麦克莱恩 伊利亚・伍德 阿伦・霍华德
   - 它的价值就在于创造的虚构世界并非是和现实世界的影子，而是人类心灵的镜子，而这曾经是儿童的专利。
** 教父 (马里奥・普佐)
   导演： 弗朗西斯・福特・科波拉
   主演： 马龙・白兰度 阿尔・帕西诺
   - 马龙白兰度扮演的这位父亲无疑是最伟大的，电影把虚构的纽约黑手党塑
     造成了一个实现美国梦的家族奋斗史。
** 乱世佳人 (玛格丽特・米歇尔)
   导演： 乔治・库克  
   主演： 克拉克・盖博 费雯・丽
   
* [[file:index.html][wiki]]
