# -*- org -*-
# -*- coding:utf-8 -*-

# Time-stamp: <2016-07-23 14:30:02 (mykulou@gmail.com)>
#+SETUPFILE: theme-bigblow-local.setup

* 系统管理相关
** linux工具集(Linux From Scratch)
    - Autoconf、Automake、Libtool、M4、Make、GCC、Glibc
    - Bash、Expect、Bison、Flex、Gawk、Perl、Sed、Tcl、Vim
    - Bzip2、Gzip、Tar、Zlib
    - Binutils 是一组开发工具，包括连接器，汇编器和其他用于目标文件和档
      案的工具。
      #+begin_src bash
	安装下列程序: addr2line, ar, as, c++filt, gprof, ld, nm, objcopy,
 	objdump, ranlib, readelf, size, strings 和 strip
      #+end_src
    - Coreutils软件包包括一整套基本的shell工具。
      #+begin_src bash
    安装下列程序: basename, cat, chgrp, chmod, chown, chroot, cksum,
    comm, cp, csplit, cut, date, dd, df, dir, dircolors, dirname, du,
    echo, env, exp和, expr, factor, false, fmt, fold, groups, head,
    hostid, hostname, id, install, join, link, ln, logname, ls, md5sum,
    mkdir, mkfifo, mknod, mv, nice, nl, nohup, od, paste, pathchk,
    pinky, pr, printenv, printf, ptx, pwd, readlink, rm, rmdir, seq,
    sha1sum, shred, sleep, sort, split, stat, stty, su, sum, sync, tac,
    tail, tee, test, touch, tr, true, tsort, tty, uname, unexp和, uniq,
    unlink, uptime, users, vdir, wc, who, whoami 和 yes
      #+end_src
    - E2fsprogs 提供用于 ext2 文件系统的工具。它还支持 ext3 日志文件系统。
      #+begin_src bash
	 安装下列程序: badblocks, blkid, chattr, compile_et, debugfs,
      dumpe2fs, e2fsck, e2image, e2label, findfs, fsck, fsck.ext2,
      fsck.ext3, logsave, lsattr, mk_cmds, mke2fs, mkfs.ext2,
      mkfs.ext3, mklost+found, resize2fs, tune2fs 和 uuidgen.
      #+end_src
    - Findutils 包含查找文件的工具，既能即时查找(递归的搜索目录，只显示
      符合要求的文件)，也能在数据库里查找。
      #+begin_src bash
	 安装下列程序: bigram, code, find, frcode, locate, updatedb 和 xargs
      #+end_src
    - Modutils包含处理内核模块时使用的工具。
      #+begin_src bash
	 安装下列程序: depmod, genksyms, insmod, insmod_ksymoops_clean,
      kallsyms (link to insmod), kernelversion, ksyms (link to insmod),
      lsmod (link to insmod), modinfo, modprobe (link to insmod) 和
      rmmod (link to insmod)
      #+end_src
    - Net-tools 包含一系列程序，构成了 Linux 网络的基础。
      #+begin_src bash
	 安装下列程序: arp, dnsdomainname (link to hostname), domainname
      (link to hostname), hostname, ifconfig, nameif, netstat,
      nisdomainname (link to hostname), plipconfig, rarp, route,
      slattach 和 ypdomainname (link to hostname)
      #+end_src
    - procinfo 从/proc目录下搜集系统信息如中断,IO接口等，并整理成易于理解的格式。
      #+begin_src bash
	 安装下列程序: lsdev, procinfo 和 socklist
      #+end_src
    - Procps软件包包含监视和终止系统进程的程序。它通过/proc目录搜集进程的信息.
      #+begin_src  bash
	 安装下列程序: free, kill, pgrep, pkill, ps, skill, snice, sysctl, tload, top, uptime, vmstat, w 和 watch
      #+end_src
** 系统
   - free、vmstat、mpstat、iostat、sar
     #+begin_src bash
free -m | grep Mem | awk '{print ($3 / $2)*100}'	#显示占用百分比
ipcs #显示有关共享内存段、IPC 消息队列以及信号的信息
ipcrm #删除共享内存、IPC 消息队列或信号数组。

vmstat 1 3	#进程数(等待运行、被阻塞)，内存(交换、可用、缓冲区、缓存)，交换和I/O活动，系统(中断、上下文切换)，CPU(用户、系统、可用、等待)
procs -----------memory---------- ---swap-- -----io---- -system-- -----cpu------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0      0 360848  16776  75416    0    0    25     3   33   36  0  0 99  1  0

mpstat 1 2	#CPU 相关统计信息
15时36分07秒  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest   %idle
15时36分08秒  all    0.00    0.00    0.00    6.00    0.00    0.00    0.00    0.00   94.00

iostat		#tps(每秒的传输数量，例如，每秒的 I/O 操作数)
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.13    0.00    0.23    0.88    0.00   98.76
Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda               1.69        21.78         3.19      84637      12392

iostat -p ALL -x	#rrqm/s(每秒合并的读请求数)，rsec/s(每秒从该设备读取的扇区数)，avgrq-sz(读请求的平均大小（扇区数）)，avgqu-sz(该设备的请求队列的平均长度)，svctm(设备的平均服务时间ms)，%util(带宽利用率)
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.12    0.00    0.22    0.89    0.00   98.77
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.28     0.42    1.35    0.36    21.00     3.17    28.22     0.03   19.19   19.84   16.78   6.09   1.04
sda1              0.01     0.00    0.06    0.00     0.29     0.00     9.68     0.00    1.92    1.92    0.00   1.88   0.01
sda2              0.26     0.42    1.19    0.36    20.28     3.17    30.39     0.03   20.83   21.96   17.05   6.67   1.03
sda3              0.01     0.00    0.07    0.00     0.29     0.00     8.88     0.00    7.65    7.73    0.00   5.54   0.04
scd0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
     #+end_src
   - lsof、ps、pstree
   - top/w/uptime/pmap/ss/strace/proc
   - iptraf
** 网络
   - ping/telnet/dig/traceroute/whois/netstat：基本命令
   - tcpdump/wireshark/netcat/hping/nmap
   - snort（入侵检测）
   - metasploit（漏洞框架）
   - john（密码破解）
   - sysinternals（全面的windows工具集）
** 其他
   - hexdump/xxd
   - df/du/fdisk
   - cron/at
* [[file:index.html][wiki]]
