# -*- org -*-
# -*- coding:utf-8 -*-

# Time-stamp: <2016-07-25 09:52:17 walker-zheng(mykulou@gmail.com)>
#+SETUPFILE: e:/zmy/emacs/.emacs.d/org-html-themes/setup/theme-bigblow-local.setup

* 历史
** 蒙古帝国
*** 和中国的关系
    1. 元帝国包括整个大蒙古国，为中国的一个朝代
       - 蒙古高原的部落有一段时间曾为金朝的附属国，而且元帝建都大都（今
         北京），管辖地主要是现在的中国的疆域。清史稿也有清朝疆土仅次于
         元之说法。
       - 蒙古诸汗国与元帝在相当长的时期内保持了法律上的宗藩关系，蒙古术
         赤汗国、蒙古察合台汗国、蒙古伊儿汗国等仍然尊大蒙古国的元帝为大
         蒙古国大汗，所以整个大蒙古国，从多瑙河到日本海，在某种意义上都
         是“大蒙古国的元帝”的疆土。
    2. 元帝国（元）是中国的一个朝代
       - 这种说法认为由忽必烈建立的元帝国是中国的一个朝代，即元，但原属
         蒙古帝国的其他汗国并不是中国的组成部分。关于元朝为中国朝代的理
         由同前一观点，但由于忽必烈违背大汗选举传统即位以及他的“行汉
         法”主张，四大汗国纷纷脱离他的统治。宗主国与藩属国并非一个国
         家，因此，元可以作为中国的一个朝代，而四大汗国则不属于中国。
    3. 元帝国为外来政权
       - 这种说法认为由于大蒙古国征伐或侵灭了多个国家，包括现位于今中国
         境内的西辽、西夏、金朝、吐蕃诸部、大理国和赵宋等，只是当时大蒙
         古国疆域的一部分。最先脱离大蒙古国统治的就是在中国地区的汉人朱
         重八建立的明朝所驱逐。
*** 死亡
    - 无数古代文献都记载，在蒙古帝国的扩张过程中，无数的古代文明遭到彻
      底毁灭，无数个城池被夷为平地，根据R. J. Rummel估计，在蒙古帝国的
      入侵下有3000万人被杀。在蒙古帝国对西方的扩张过程中有2,000万人被屠
      杀；整个亚洲的人口分布亦发生重大变化。“恐怖和大规模灭绝反对者是
      蒙古人屡试不爽的战术”。
    - 中国人口在蒙古入侵的七十年间因战争和包括因战争造成的各种原因被消
      灭了一半。在蒙古入侵以前（1200年），中国（包括金朝、西夏、赵宋、
      大理国）人口约有1亿4千4百万，甚至更多，而到1278年（1279年完全占
      领）只有7,000万人
    - 细菌战传播鼠疫，在欧洲广泛传播，最终在1348年―1349年造成2,000万人
      死亡，使得当时欧洲丧失了三分之一的人口
    - 从1219年到1260年，由于大屠杀和饥荒，波斯的总人口从1200万下降到110
      万。在花剌子模沙朝的七十多个城市，都被蒙古军大规模屠杀和摧毁村庄，故
      意大量杀死当地百姓，有的城市甚至被多次屠杀，给当地造成巨大灾难和
      痛苦记忆。历史学家估计匈牙利王国（1241年―1242年）当时200万人口中
      的一半在拔都进攻下都死于蒙古入侵。
**** 耶律楚材
     - 改变屠城传统，着重富国保民
     - 国家兴兵打仗，就是为了得到土地和人民，得地无民，又有何用！奇工巧
       匠、富厚之家皆荟萃于此城中，若悉数屠戮，入城将一无所获
**** 丘处机
     - 并因远赴西域劝说成吉思汗减少屠杀而闻名
     - 丘处机对成吉思汗的劝说，稍微减少了蒙古帝国进攻金国时的屠杀和破坏
*** 评价
    - 在蒙古、中亚附近，多达8%的男性人类是成吉思汗的直系后代，全球有至
      少1,600万这样的男子
    - 最环保的侵略者，因为杀人无数，让大片耕地恢复成为森林
*** 征服王朝
    - 魏复古将中国历史朝代分成两类：一个是汉族建立的朝代，称为中原王朝，另
      一个是由四周少数民族（大多是北方民族）所建立的朝代，其中又分成渗
      透王朝与征服王朝。
    - 渗透王朝：东汉末期到西晋时期时，匈奴、羯、羌、氐与鲜卑等族，自塞
      外内徙，乘西晋末年八王之乱后先后在中原建立国家与朝代，例如五胡十
      六国如前赵、后赵、后秦、前秦与前燕等等国家，北朝各国如北魏、北周
      等朝代。另一波则是唐朝末期到五代十国期间，被汉化的沙陀藩镇建立的
      朝代与国家，例如后唐、后晋与后汉等。这些朝代与国家吸收汉文化并且
      最后彻底被汉化。虽然这些民族或曾反抗汉化，如北魏的六镇之乱与北齐
      皇帝抵制汉化都是反对汉化的例子，然而最后仍然被汉化掉。
    - 征服王朝：唐朝之后的契丹、党项、女真、蒙古与满洲等族，于唐末、五
      代与宋朝（满洲是明末）时，占领中原一部分或全部领地，分别建立辽朝、
      西夏、金朝、元朝与清朝等朝代。这些民族一开始就选择性的摄取汉化，
      并且维护自身文化。

** 人口流动
*** 迁徙
    - 大西洋奴隶贸易
      - 在长达约400年的带有强烈殖民主义色彩的黑奴贸易中，目前估计约有
        1200万人从非洲运到美洲的奴隶，将航运死亡的一千万人计算入内后，
        非洲人口损失数据可以达到三千万
    - 美国西进运动
    - 中国
      - 衣冠南渡，八姓入闽
      - 洪武赶散
      - 湖广填四川
      - 江西填湖广
        
** 灾难
** 反智主义
*** 文化大革命
     - 非正常死亡在5755万人以上
     - 红卫兵所带来的破坏不仅是对于中国历史文物及伦理道德的摧残，道德
       沦丧，腐败成风，经济文化停滞甚至倒退
*** 焚书坑儒
    - 秦始皇摧毁了大量先秦典籍，数千年中国所收藏的海量文献几乎消失殆尽

** 文化
*** 控制
    - 焚书坑儒
*** 屠夫
    - 白起(公孙启)
      - 杀人一百余万以上，据梁启超考证，整个战国期间共战死两百万人，白
        起就占二分之一
    - 曹操
      - 曾发动多次屠城，受到屠杀的战俘与平民达数十万之多，每到一处，都
        实行杀光政策
    - 黄巢
      - 野史有称“黄巢杀人八百万”恶名，嗜好滥杀无辜，粮草短缺
    - 铁木真
      - 公元1215年，铁木真攻陷金国都城中都(北京)，对城中居民进行了长达
        一个月之久的大屠杀，超过100万人未能幸免；公元1221年，铁木真第
        一次西征，对撒马尔罕进行了疯狂屠杀。当时蒙古兵有5万人，平均每
        人杀死24人，共计120万
    - 忽必烈
      - 施行种族灭绝政策，大肆屠杀汉人、南人累计1800万之多，中国北方
        90%汉族平民几乎惨遭种族灭绝。四川在屠杀前，估计有1300-2000多万
        人，屠杀后竟然不满80万人，几乎成了无人区
    - 朱元璋
      - 大杀功臣、朝臣，杀了二十万，基本上将功臣杀光
    - 朱棣
      - 夺皇位，建文帝宫中的宫人、女官、太监几乎被杀绝，一次就枉杀了
        14000多人。方孝儒灭“十族”等。永乐末年，他又大肆屠杀宫女、宦
        官，在这次大惨案中，被杀的宫女有近3000人之多
    - 张献忠
      - 攻陷成都后，屠城三日。在大军逃离成都前，更是对成都实行残酷的
        “四光政策”，尽杀蜀人，
    - 多铎
      - 扬州十日，由城内僧人收殓的尸体就超过了80万具

        

