# -*- org -*-
# -*- coding:utf-8 -*-

# Time-stamp: <2016-07-23 14:35:37 (mykulou@gmail.com)>
#+SETUPFILE: theme-bigblow-local.setup

* 枪炮、病菌与钢铁
** 第一部分 从伊甸园到卡哈马卡
*** 一、 关于人类进化和历史的旋风式的旅行
    - 大约4万年前，克罗马努人带着他们现代人的体格、优良的武器和其他先
      进的文化特征进入欧洲。不出几千年，尼安德特人不复存在，虽然几千年
      来，他们作为欧洲唯一的居民，一直在这块土地上繁衍生息o这个结果有
      力地表明了，现代的克罗马努人以某种方式利用他们的远为优良的技术和
      他们的语言技能或智力，用病菌传染、杀害或取代了尼安德特人，而又很
      少或根本没有任何证据可以证明尼安德特人和克罗马努人之间的混合现象。
    - 毛利人的祖先在到达新西兰后，他们显然花了几乎不到100年时问就发现了
      各种有价值的石材资源；又花了仅仅几百年时间就在世界上—些最高低不平
      的地区把恐鸟全部杀死；又花了仅仅几百年时间分化成一系列形形色色的社
      会，从沿海狩猎采集社会到进行新型粮食贮藏的农民社会。
    - 澳大利亚/新几内亚移民：第一次使用水运工具和扩大活动范围，人类第
      一次大规模灭绝大型动物物种
    - 澳大利亚几内亚所有大型动物的消失对其后的人类历史带来了严重的后果。
      这些动物绝种了，本来可以用来驯化的所有大型野生动物也就被消灭了，
      这就使澳大利亚土著和新几内亚人再也没有一种属于本地的家畜了
      
*** 二、 简要地考察了岛屿环境在较小的时空范国内对历史的影响
    - 波利尼西亚的岛屿社会在其经济专业化、社会复杂程度、政治组织以及物质
      产品方面存在着巨大的差异。这些差异与人口的数量和密度的差异有关，又
      与岛屿的面积、地形破碎程度和隔离程度有关，也与维持生存和加强粮食生
      产的机会有关
    - 莫里奥里人是一个很小的与世隔绝的族群，他们是以狩猎采集为生的人，
      他们所学握的仅仅是最简单的技术和武器，对打仗毫无经验，也缺乏强有
      力的领导和组织。毛利人人侵者(来自新西兰的北岛)来自人口稠密的农
      民，他们长期从事残酷的战争，装备有比较先进的技术和武器，并且在强
      有力的领导下进行活动。当这两个群体发生接触时，当然是毛利人屠杀莫
      里奥里人，而不是相反。
    - 毛利人和莫里奥里人的这次冲突使人们了解到一个可怕事实，原来这两
      个群体是在不到1000年前从同一个老祖宗那里分化出来的。
    - 所有现代波利尼西亚人的最初祖先基本上都具有同样的文化、语言、技术
      和一批驯化的动植物。波利尼西亚人的生存方式从查塔姆群岛上以狩猎采
      集为生的人，到刀耕火种的农民，到生活在不管哪种人类社会都算得上人
      口密度最高的某些地区从事集约型粮食生产的人。      
    - 新西兰的北部(比较温暖)是波利尼西亚的最大岛群，适宜于波利尼西亚的
      农业。他们在局部地区形成了密集的人口，这些人长期从事与邻近居民的
      残酷战争。由于他们栽种的农作物有剩余并可用来贮藏，他们养活了一些
      专门的手艺人、首领和兼职士兵。他们需要并制作了各种各样的工具，有
      的用来栽种农作物，有的用来打仗，还有的用来搞艺术创作。他们建造了
      精致的用作举行仪式的建筑物和为数众多的城堡。
    - 在波利尼西亚群岛之间，至少有6种环境可变因素促成了波利尼西亚社会
      之间的这些差异：岛屿气候、地质类型、海洋资源、面积、地形的破碎和
      隔离程度。
    - 较高火山岛的海拔高度给山地带来了雨水，所以这些岛屿受到风雨的严重
      侵蚀，有很厚的土壤和长年不竭的溪流。在较低的岛屿中，汤加群岛和
      (在较小程度上的)复活节岛由于火山灰的缘故土壤也很肥沃，但它们没有
      夏威夷群岛上的那种大溪流。
    - 波利尼西亚人赖以生存的手段五花八门：捕鱼，采集野生植物、捕捞海洋
      有壳动物和甲壳动物，猎捕陆栖鸟和繁殖季节的海鸟，以及生产粮食。波
      利尼西亚大多数岛屿原来都有一些大型的不会飞的鸟，它们是在没有食肉
      动物的情况下演化出来的，新西兰的恐鸟和夏威夷的不会飞的野鹅就是这
      方面最著名的例子。虽然这些鸟是最早移民的重要的食物来源，在新西兰
      的南岛上尤其如此，但其中大多数在所有岛屿上很快灭绝了，因为它们很
      容易被迫捕到。繁殖季节的海鸟数目也很快减少，但在有些岛上，它们仍
      然是重要的食物来源。海洋资源对大多数岛屿来说都是意义重大的，但对
      复活节岛、皮特凯恩群岛和马克萨斯群岛来说却最不重要，因为那里的人
      主要依靠自己生产的食物为生。
    - 其他一些岛屿虽然土壤肥沃，但因高度不够而没有长年不竭的大溪流，因
      此也就没有港溉之利。这些岛上的居民发展了集约型的旱地农业，这需要
      投入很大劳动力来修筑梯田，用覆盖料覆盖地面，进行轮作，减少或取消
      休耕期，以及养护林场。早地农业在复活节岛、小小的阿努塔岛和低平的
      汤加岛尤其多产，这些地方的波利尼西亚人把他们的大部分土地专门用来
      种植粮食作物。
    - 在夏威夷群岛最西端的考爱岛、瓦胡岛和莫洛凯岛，灌溉农业达到了顶
      峰，因为这些岛屿面积较大而又潮湿，不但有长年不竭的大溪流，而且还
      有可以用来从事建筑工程的众多人口。夏威夷用强征劳动力修建了浇灌芋
      艿田的复杂的灌溉系统，使每英亩芋艿产量达到24吨，是整个波利尼西亚
      农作物的最高产量。这些产量反过来又支援了集约型的养猪事业。在利用
      大规模劳动从事水产养殖方面，夏威夷在波利尼西亚群岛中也是独一无二
      的，那就是它修建了一些大型鱼塘来放养遮目鱼和缁鱼。
    - 一个行政单位人口的多少，与其影响波利尼西亚人的技术及经济、社会和
      政治组织的人口密度互相作用。一般地说，人口越多，人口密度越高，技
      术和组织就越复杂，专业程度就越高。人口密度高时，只有一部分人最后
      成为农民，但他们被调动起来去专门从事集约型的粮食生产，从生产出剩
      余粮食去养活非生产者。能够调动农民的非生产者包括首领、神职人员、
      官员和战士。最大的行政单位能够调集大批劳动力来修建进一步加强粮食
      生产的灌溉系统和鱼塘
    - 首领任命官员做代理人，利用他们向平民征用粮食，同时征召平民从事大
      型建筑工程的劳动，这些工程项目因岛而异：在夏威夷是灌溉工程和鱼
      塘，在马克萨斯群岛是舞蹈和宴会中心，在汤加是首领的陵墓，在夏威夷、
      社会群岛和复活节岛是庙宇。
    
*** 三、 卡哈马卡的冲突
    - 文化修养使西班牙人继承了关于人类行为和历史的大量知识；用文字来传
      播信息，要比用口头传播来得广泛、准确和详细；除了航海技术、船只本
      身，皮萨罗的出现还依赖于集中统一的行政组织。有了这种组织，两班
      牙才能为这些船只提供资金、建造技术、人员和装备。具有相当免疫力
      的入侵民族把疾病传染给没有免疫力的民族；马匹使得骑马的人能够通过
      比步行远得多的距离，去进行奇袭，并在防御部队集合前逃之夭夭。
    - 皮萨罗成功的直接原因包括：以枪炮、钢铁武器和马匹为基础的军事技
      术；欧亚大陆的传染性流行病；欧洲的航海技术；欧洲国家集中统一的行
      政组织；和文字。
    - 
** 第二部分 粮食生产的出现和传播
*** 四、 农民的力量
    - 从间接的意义说，粮食生产是枪炮、病菌和钢铁发展的一个先决条件。
    - 第一个因果关系是最直接的因果关系：能够获得更多的可消耗的卡路里就
      意味着会有更多的人。通过对我们能够吃的那几种动植物的选择、饲养和
      种植，使它们构成每英亩土地上的生物量的90％而不是0．1％，我们就能
      从每英亩土地获得多得多的来自食物的卡路里。结果，每英亩土地就能养
      活多得多的牧人和农民——一般要比以狩猎采集为生的人多l0倍到100倍。
    - 人类的各种各样疾病是在有许多适于驯化的动植物物种的地区演化的，这
      一部分是由于生产出的农作物和饲养的牲畜帮助养活了使流行疾病得以保
      持的人口稠密的社会；一部分是由于这些疾病是从驯化的动物身上的病菌
      演化而来。
    - 在饲养驯化动物的人类社会中，牲畜在4个不同的方面养活了更多的人：
      提供肉类、奶脂、肥料以及拉犁。最直接的是、家畜代替野生猎物而成为
      社会主要的动物蛋白来源。
    - 所有这些都是出于动植物驯化比狩猎采集的生活方式能生产出更多的食物
      从而导致更稠密人口的一些直接因素。一个比较间接的因素是与粮食生产
      所要求的定居生活方式的后果直接有关的。粮食生产者的这种较高的出生
      率，加上他们按每英亩计算养活更多的人的能力，使他们达到了比狩猎采
      集部族更大的人口密度。
    - 定居生活的另一个结果是人们可以把多余的粮食贮藏起来。但贮藏的粮食
      对于养活不生产粮食的专门人材是必不可少的，而对于养活全村社的人肯
      定是必不可少的
    - 这些复杂的行政单位比平等之主义的猎人群体能更好地发动持久的征服战
      争。通过税收建立剩余粮食储备，除了养活国王和官员外，还能养活其他
      专职的专门人材。与征服战争关系最直接的是，剩余粮食储备可以用来养
      活职业军人。粮食储备还可以养活为征服战争提供宗教理由的神职人员，
      养活像制造刀剑、枪炮和发展其他技术的金属加工工人之类的手艺人，以
      及养活能够保存信息的抄写员，因为他们所记录的信息比人们能够准确记
      住的信息要多得多
    - 农作物和家畜生产出的天然纤维，可以用来做衣服、毯子、网和绳子。
    - 驯化的大型哺乳动物在19世纪铁路发展起来之前成为我们主要的陆路运输
      手段，从而进一步使人类社会发生了革命性的剧变。在人类历史上第一次
      有可能迅速地不但把人而且也把大量沉重的货物从陆路运到很远的地方去。
      供人骑乘的驯化动物有马、驴、牦牛、驯鹿、阿拉伯单峰驼和中亚双峰驼。
      这5种动物和羊驼一样，都被用来背负行囊包裹。牛和马被套上大车，而
      驯鹿和狗则在北极地区拉雪橇。在欧亚大陆大部分地区，马成了长距离运
      输的主要手段。3种驯化骆驼(阿拉伯单峰驼、中亚双蜂驼和羊驼)分别在
      北非地区和阿拉伯半岛、中亚和安第斯山脉地区起着类似的作用。
    - 动植物驯化对征服战争的最直接的贡献是由欧亚大陆的马作出的，它们在
      军事上的作用，使它成了那个大陆上古代战争中的吉普车和谢尔曼坦克。
      当马在后来被套上马车和其他车辆时，马拉战车(公元前1800年左右发明)
      开始在近东、地中海地区和中国使战争发生了革命性的剧变。
    - 在马鞍和马镫发明后，马使来自亚洲大草原的匈奴人和一波接一波的其他
      民族对罗马帝国和后继国家造成了威胁，最后以蒙古人于公元13世纪和14
      世纪征服亚洲和俄罗斯的许多地方而达到高潮。
    - 在征服战争中同样重要的是在驯养动物的社会中演化的病菌。从驯养的动
      物那里通过这一途径而最后获得的病菌，在欧洲人对美洲、澳大利亚、南
      非和太平洋诸岛的土著的征服中起了决定性的作用。
    - 动植物的驯化意味着人类的粮食越来越多．因而也就意味着人口越来越稠
      密。因此而带来的粮食剩余和(在某些地区)利用畜力运输剩余粮食，成了
      定居的、行政上集中统一的、社会等级分明的、经济上复杂的、技术上富
      有革新精神的社会的发展的先决条件。
    - 因此，能否利用驯化的动植物，最终说明了为什么帝国、知书识字和钢铁
      武器在欧亚大陆最早发展起来，而在其他大陆则发展较晚，或根本没有发
      展起来。在军事上使用马和骆驼以及来自动物的病菌的致命力量，最后就
      把粮食生产和征服之间的许多重要环节连接了起来
*** 五、 历史上的穷与富
    - 为什么粮食生产首先在看似相当贫瘠的土地上形成．只是到后来才在今天
      最肥沃的农田和牧场发展起来?
    - 碳是生命的无所不在的基础材料，它的成分中有很少量的放射性碳—14，
      而碳—14会衰变为非放射性同位素氮—14。宇宙射线不断地在大气中生成
      碳—14。植物吸收大气中的碳，其中碳—14和普遍存在的同位素碳—12保
      持着—种已知的几乎不变的比例(约1与100万之比)。植物中的碳接下去构
      成了吃这些植物的食草动物的躯体，也构成了吃这些食草动物的食肉动物
      的躯体。不过，这些植物或动物一旦死去，它们体内碳—14含量的一半每
      隔5700年衰变为碳—12，直到大约4万年后，碳—14含量变得很低而很难
      测出，也很难把它同受到少量的含有碳—14的现代材料的污染区别开来。
    - 世界上只有几个地区发展了粮食生产，而且这些地区发展粮食生产的时间
      也差异甚大。一些邻近地区的狩猎采集族群从这些核心地区学会了粮食生
      产．而其他一些邻近地区的族群则被来自这些核心地区的粮食生产者所更
      替了——更替的时间仍然差异甚大。最后，有些族群虽然生活在一些生态
      条件适于粮食生产产的地区．但他们在史前期既没有发展出农业，也没有
      学会农业；他们始终以狩猎采集为生，直到现代世界最后将他们淘汰。在
      粮食生产上具有领先优势的那些地区里的族群，因而在通往枪炮、病菌和
      钢铁的道路上也取得了领先的优势。其结果就是富有社会与贫穷社会之间
      一系列的长期冲突。

*** 六、 种田还是不种田
    - 因为作为狩猎采集族群的不利条件似乎是显而易见的。科学家们经常引用
      托马斯·霍布斯”的话来形容狩猎采集族群的生活方式：“凶险、粗野、
      短命。”
    - 即使是在粮食生产以最快的速度从狩猎采集的生活方式独立发展起来的情
      况下，也要花上几千年时间才能从完全依赖野生食物转变为依赖很少几种
      野生食物。在粮食生产的早期阶段，人们采集野生食物和培织非野生食物
      是同时进行的，而随着对作物的依赖的增加，各种采集活动在各个时期的
      重要性减少了。
    - 这种转变是逐步实现的，其根本原因是，粮食生产制度的渐次形成乃是许
      多关于时间和劳力分配的不同决定积累的结果。觅食的人同觅食的动物一
      样，只有有限的时间和精力，但他们花费时间和精力的方式却可以是多种
      多样的。
    - 以最少的时间、最小的努力和最大的把握产生最大的回报的方法去寻找
      食物，从而追求在卡路里、蛋白质或其他特别的食物品种方面得到最大限
      度的回报。同时，他们也追求最小限度的风险：同按平均时间计算回报率
      很高但也很可能饿死的一种变化不定的生活方式相比，适中的然而可靠的
      回报显得更为可取。
    - 我们必须把粮食生产同狩猎采集看作是相互竞争的供选择的办法。在狩猎
      采集外再种植某些作物或饲养某些牲口的混合经济，不但在和这两种“纯
      粹”经济竞争，而且也在和粮食生产比例或高或低的混合经济竞争。尽管
      如此，在过去的1万年中，普遍的结果—直是从狩猎采集转变为粮食生产。
    - 普遍的结果—直是从狩猎采集转变为粮食生产
      1. 获得野生食物的可能性减少了。
      2. 正如野生鸟兽资源的枯竭往往使狩猎采集活动好处不大一样，由于获
         得可驯化野生植物的可能性增加 了，对植物进行驯化的做法可以得到
         较大的好处。
      3. 粮食生产可能最后依赖的一些技术--对野生粮食的收集、加工和贮
         藏的技术的长期发展
      4. 人口密度增加和粮食生产出现这两者之间的相互关系
      5. 采纳粮食生产为所谓的自身催化过程提供了例证——这是一个在正反
         馈循环中自身催化的过程，这个过程一旦开始，速度就越来越快。
      - 人口密度的逐步增加，迫使人们去奖励那些无意中增加了粮食产量的
        人，以获得更多的粮食。一旦人们开始生产粮食并过定居的生活，他们
        就能够缩短生育间隔期，生出更多的人来，从而也就需要更多的粮食。
      - 有几个直到20世纪仍然以狩猎采集为生的族群所以能逃脱被粮食生
        产者取代的命运，是因为他们局处一隅，生活在一些不适于粮食生
        产的地区，尤其是在沙漠和北极地区。在当前的10年之内，即便是
        他们也会受到文明的诱惑，在政府官员或传教上的压力下定居下来，或
        听任病菌的摆布。
        
*** 七、 怎样识别杏仁
    - 就植物来说，我们不过是无意间“驯化”了植物的成千上万种的动物之一
    - 果实好吃的植物让动物来撒播它们的种子，但果实里的种子必须很难吃。
      否则，动物就会把种子嚼碎，种子也就发不出芽来了。
    - 如果说大小和味道是狩猎采集族群选择野生植物的最明显的标准，那么其
      他标准则包括果实肉多或无子、种子含油多以及纤维长。
    - 如果实的大小、苦味、多肉、含油和纤维的长度。通过收获这些具有特别
      可取的品质的野生植物，古代人在无意识中传播了这些植物，使它们走上
      了驯化之路。
      1. 第一个这样的改变影响了种子传播的野生结构。
      2. 野生植物赖以减少损失的一种普通的适应性变化，是把它们的种子裹
         在一层厚厚的皮壳或保护层中。
    - 农业耕作也改变了植物的环境。经过松土、施肥、浇水和除草的园地所提
      供的生长环境，完全不同于山坡上干燥、未施肥的园地。植物在驯化中所
      产生的许多变化都来自此类条件的变化，因此也就有了那些处于有利条件
      的植物品种的变化。
    - 今天的谷物占人类消耗的全部卡路里的半数以上，并包括现代世界上12种
      主要作物中的5种(小麦、玉米、稻米、大麦和高粱)。许多谷类作物蛋白
      质含量低，但这一缺陷可以由豆类来弥补，因为豆类的蛋白质通常达
      25%(大豆为38％)。因此，谷物和豆类一起为均衡饮食提供了许多必不可
      少的成分。
    - 当地谷物和豆类组合的驯化，标志着许多地区粮食生产的开始。最为人熟
      知的例子，是新月沃地的小麦和大麦与豌豆和兵豆的组合，中美洲的玉米
      与几种豆类的组合，以及中国的稻米和小米与大豆和其他豆类的组合。不
      大为人所知的是非洲高粱、非洲稻米和珍珠稗与豇豆和野豆的组合，以及
      安第斯山脉的非谷类的昆诺阿藜与几种豆类的组合。
    - 农业体系中的另一个重大差异涉及卡路里和碳水化合物的主要来源问题。
      我们已经看到，在许多地区，这方向的主要来源是谷物。小过，在另一些
      地区，谷物的这一任务被根和块茎接管了或分担了，显然根和块茎在古代
      的新月沃地和中国是无关紧要的。
    - 橡树生长缓慢和松鼠行动迅速这些问题大概也说明了为什么山毛榉和山核
      桃树同样未能驯化的原因，虽然欧洲人和美洲土著分别对这两种树种大量
      地加以利用以获得它们的坚果。杏仁的苦味由单一的优势基因所控制，而
      橡实的苦味似乎由许多基因所控制
    - 至于草莓和树莓，我们在与鸫和其他吃浆果的鸟儿的竞争中遇到了同样的
      困难。由于千百万只欧洲鸫把野草莓的种子排泄在每一个可能的地方(包
      括罗马人的园子里)，所以草莓始终是鸫想要吃的小浆果，而不是人想要
      吃的大浆果。
*** 八、 问题在苹果还是在印第安人
    - 仅仅十几种作物的产量，就占去了现代世界全部作物年产量总吨效的80％
      以上。这十几种了不起的作物是谷类中的小麦、玉米、稻米、大麦和高
      梁；豆类中的大豆；根或块茎中的马铃薯、木薯和甘薯；糖料作物中的甘
      蔗和糖用甜菜以及水果中的香蕉。光是谷类作物现在就占去了全世界人口
      所消费的卡路里的一半以上。由于世界上的主要作物如此之少，它们又都
      是在几千年前驯化的，所以世界上的许多地区根本就不曾有过任何具有显
      著潜力的本地野生植物，这就不足为奇了。我们在现代没有能驯化甚至一
      种新的重要的粮食植物，这种情况表明，古代人也许真的探究了差不多所
      有有用的野生植物，并且驯化了所有值得驯化的野生植物。
    - 新月沃地植物群的有利条件；
      1. 它地处所谓的地中海气候带内，这种气候的特点是冬季温和而湿润，
         夏季漫长、炎热而干燥。谷类和豆类已经适应了当地的环境，是一年
         生植物，就是说这种植物本身会在干旱季节逐渐枯萎死去。其中有许
         多把自己的很大一部分气力用来生产大籽粒的种子，种子在旱季休眠，并
         准备好在雨季到来时发芽。
      2. 新月沃地许多作物的野生祖先本就繁茂而高产，它们大片大片地出现，对
         于狩猎采集族群来说，其价值必定是显而易见的。新月沃地的有些狩
         猎采集族群在种子成熟的短暂时间里采集大量的野生植物，并把它们
         作为粮食贮存起来以备一年中其余时间之需，这样，他们甚至在开始
         栽培植物之前就己在永久性的衬庄里定居了下来。
      3. 雌雄同株自花传粉的植物比例很高。
    - 原来地中诲气候带，尤其是在新月沃地那个地区，具有胜过其他地中海气
      候带的5个有利条件。
      1. 欧亚太陆西部显然是世界上属于地中海气候带的最大地区。因此，那
         里的野生动植物品种繁多，超过了澳大利亚西南部和智利这些比较小
         的地中海气候带。
      2. 在地中海气候带中，欧亚大陆西部的地中海气候带的气候变化最大，
         每一季、每一年气候都有不同。这种气候变化有利于植物群中数量特
         别众多的一年生植物的演化。物种多和一年生植物多这两个因素结合
         起来，就意味着欧亚大陆西部的地中海气候带显然是一年生植物品种
         最繁多的地区。
         - 全世界56种最有价值的野生禾本科植物中的大约32种[特别是，在居
           首位的这56种作物中，新月沃地最早的两种作物大麦和二粒小麦在
           种子大小方面分别列第三位和第十三位。相比之下，智利的地中海
           型气候带只有两种，加利福尼亚和非洲南部各有一种，而澳大利亚
           西南部连一种都没有。仅仅这一事实就很有助于说明人类历史的进
           程。
      3. 是它在短距离内高度和地形的富于变化。新月沃地的高度变化意味着
         可以把收获季节错开：高地植物结籽比低地植物多少要晚一些
      4. 新月沃地在很小距离内的生物多样性。那里不仅有大量的重要作物的
         野生祖先，而且也有大量的得到驯化的大型哺乳动物的野生祖先。
         - 新月沃地的农业开始于对所谓8大“始祖作物”的早期驯化(因为是
           这些作物开创了这一地区的、可能还有全世界的农业)。这8大始祖
           作物是谷类中的二粒小麦、单粒小麦和大麦；豆类中的兵豆、豌豆、
           鹰嘴豆和苦巢菜；以及纤维作物亚麻。
      5. 同包括西地中海沿岸在内的一些地区相比，那里所面临的来自狩猎采
         集生活方式的竞争可能要少一些。
         - 西南亚很少有大江大河．只有很短的海岸线，所以那里较少水产资
           源(如江河和近海鱼类及有壳水生动物)。在那里，为了肉食而被人
           猎杀的哺乳动物之一是瞪羚。瞪羚本来是群居动物，但因人口增加
           而被过度利用，数目已大大减少。因此，粮食生产的整个好处很快
           就超过了狩猎采集的整个好处。
    - 由于能够得到合适的野生哺乳动物和植物，新月沃地的先民们能够为集约
      型粮食生产迅速装配起一个有效而平衡的生物组合。这个组合包括作为碳
      水化合物主要来源的3种谷物，作为蛋白质主要来源的4种豆类(含蛋白质
      20％至25％)和4种家畜，再以小麦的丰富蛋白质为补充；以及作为纤维和
      油(叫做亚麻籽油：亚麻籽含有约40％的油)的一个来源的亚麻。最后．在
      动物驯化和粮食生产出现的几千年后，这些动物也开始被用来产奶和剪
      毛，并帮助人类犁田和运输。因此，新月沃地最早的农民的这些作物和牲
      畜开始满足人类的基本经济需要：碳水化合物、蛋白质、脂肪、衣着、牵
      引和运输。
    - 关于第一个问题，有一门叫做人种生物学的学科专门研究人对其环境中
      的动植物的了解程度。这门学科的研究对象主要是世界上幸存的为数很
      少的狩猎采集族群以及仍然严重依赖野生食物和自然产品的农业部族。
      这些研究普遍表明，这些族群是博物学的活的百科全书，他们叫得出
      (用当地语言)多达1000种或更多的动植物的名称，他们对这些物种的生
      物学特点、地理分布和潜在用途具有详尽的知识。随着人们越来越依赖
      已经驯化的动植物，这种传统知识逐渐失去了价值，甚至已经失传，直
      到人们成了连野草和野豆也分不清的现代超市上的购物者。
    - 关于古代族群如何明显地充分利用他们的人种生物学知识这个问题
      1. 最早的农民继承了这方面的知识，这是生活在对自然界的密切依赖之中的
         生物学上的现代人类经过几万年对自然界的观察而积累起来的知识。因
         此，具有潜在价值的野生物种竟会逃过最早的农民的注意，这看来是极不
         可能的。
      2. 特勒阿布朗瑞拉的狩猎采集族群并没有把时间浪费在不加区别地去采集可
         能危及自己生命的野生植物。相反，他们同现代的新几内亚人一样，显然
         对当地的野生植物有深刻的了解．所以他们就利用这种知识只去选择现有
         的最有用的种子植物并把它们带回家。但是，这些被收集来的种子竞构成
         了促使植物驯化迈出无意识的第一步的材料。
      3. 23种种子最好吃的也是最大的野生禾本科植物。大麦和二粒小麦在被选之
         列，这是毫不奇怪的。大麦和二粒小麦从许多标准看都是最好的。二粒小
         麦的种子最大，大麦的种子次大。在野生状态中，大麦是23种中产量最高
         的4种之一，二粒小麦的产量属于中等。大麦还有一个优点：它的遗传性
         和形态使它能够迅速形成我们在前一章所讨论的种子传播和发芽抑制方面
         的变化。然而，二粒小麦也有补偿性的优点：它比大麦容易采集，而且它
         还有一个不同于其他谷物的独特之处，因为它的种子容易和外壳分离。至
         于其他21种禾本科植物的缺点包括：种子较小．在许多情况下产量较低，
         在有些情况下它们是多年生植物，而不是一年生植物，结果它们在驯化过
         程中的演化反而会变得很慢。
    - 地球上不同地区的当地作物并不是同样多产的。
      - 采纳粮食生产涉及粮食生产的生活方式与狩猎采集的生活方式之间的竞
        争。在新几内亚，狩猎采集的回报还没有丰厚到可以打消发展粮食生产
        的积极性。尤其是，现代新几内亚的猎人由于野生猎物的不足而处于受
        到严重损害的不利地位
    - 新几内亚的生物区系受到3个方面的严重限制：
      1. 在新几内亚没有任何驯化的谷类作物，而在新月沃地、萨赫勒地带和
         中国都有几种极其重要的谷类作物。新几内亚重视根用作物和树生作
         物。世界上56种种子最大的野生禾本科植物没有一种是生长在那里的。
      2. 新几内亚的动物群中没有任何可以驯化的大型哺乳动物。现代新几内
         亚驯养的动物只有猪、鸡和狗，它们也都是在过去几千年中经由印度
         尼西亚从东南亚引进的。虽然新几内亚的低地居民从他们捕捉到的鱼
         类获得了蛋白质，但新几内亚的高原地区的居民在获得蛋白质方面受
         到严重的限制。新几内亚高原地区的儿童患有膨胀病，新几内亚人无
         分老幼，常常吃老鼠、蜘蛛、青蛙和其他小动物。
      3. 以往新几内亚能够得到的根用作物不但蛋白质少，而且卡路里也不高，因
         为这些作物在如今生活着许多新几内亚人的高地上生长不好。甘薯引
         进的结果是高原人口激增。
    - 由于当地没有可以驯化的谷物、豆类植物和动物，由于因此而带来的高
      原地区蛋白质的缺乏，同时也由于高原地区当地现有根用作物的局限，
      他们的土生土长的粮食生产受到了限制。不过，新几内亚人对他们现有
      的野生动植物的了解，一点也不比今天地球上的任何民族差。他们同样
      能够发现并检验任何值得驯化的野生植物。他们完全能够认出在他们现
      有的作物之外的其他一些有用的作物，他们在甘薯引进时兴高采烈地接
      受了它就是证明。因此．新几内亚土生土长的粮食生产所受到的限制与
      新几内亚的族群没有任何关系，而是与新几内亚的生物区系和环境有着
      最密切的关系。
    - 原来美国东部的始祖作物是4种植物，它们在公元前2500年至l 500年这一
      时期得到驯化，比新月沃地的小麦和大麦的驯化时间晚了整整6000年。当
      地的一种南瓜属植物不但能产生可吃的种子，而且还可用作小型容器。其
      余3种始祖作物完全是因为它们的可吃的种子才被人栽种的(向日葵、一种
      叫做菊草的雏菊亲缘植物和一种叫做藜的菠菜远亲植物)。但4种种子作物
      和一种容器远远够不上完全的粮食生产组合。直到公元前500年至200年这
      一时期，在又有3种种子作物(扁蓄、五月草和小大麦)得到栽培之后，农
      业才成为他们食品的主要部分的来源。
      - 美国东部的这些作物的大多数虽然在营养方面有其优点，但它们在其他
        方面也存在严重的缺点。藜属植物、扁蓄、小大麦和五月草的种子很
        小，体积只有小麦和大麦种子的十分之一。更糟的是，菊草是靠风媒传
        粉的豚草的亲缘植物，而豚草是众所周知的引起花粉病的植物。同豚草
        的花粉一样，凡是在菊草长得茂盛的地方，菊草的花粉都会引起花粉病。
        如果这一点还不能使你想要做一个种植菊草的农民的热情完全稍失的
        话，就请你注意它有一种今某些人讨厌的强烈气味，而且接触到它会引
        起皮肤过敏。
      - 而在公元1100年左右随着豆类的引进，墨西哥的玉米、豆类和南瓜类这
        三位一体的作物便齐全了。美国东部的农业大大地集约化了，人口稠密
        的酋长管辖的部落沿密西西比河及其支流发展了起来。
        - 在美国东部所有这些古代特有作物中，只有2种(向日葵和东部南瓜)
          能够同在其他地方驯化的作物相媲美，并且至今仍在种植。我们现代
          的橡实形南瓜和密生西葫芦就是从几千年前驯化的美洲南瓜属植物演
          化而来的。
      - 直到公元900年之后，墨西哥三位一体的作物组合才引发了人口的较大
        增长，即所谓的密西西比文化的繁荣。人口的增长使墨西哥以北的印第
        安人得以建设最大的城镇和最复杂的社会。但这种人口的增长毕竟来得
        太晚，没有能使美国的印第安人为迫在眉睫的欧洲人殖民灾难作好准备。
      - 同在新几内亚一样，美国东部土生土长的粮食生产所受到的限制，不是
        由于印第安人本身，而是完全决定于美洲的生物区系和环境。
      - 我们发现，新月沃地、新几内亚和美国东部的这些差异，直接来自可以
        用来驯化的野生动植物的不同系列，而不是来自这些族群本身的局限性。
        当更多产的作物从别处引进时(新几内亚的甘薯，美国东部的墨西哥三
        位一体的作物)，当地族群迅即利用了它们，加强了粮食生产，从而大
        大地增加了人口。如果把范围加以扩大．依我看在地球上的一些根本没
        有在当地发展出粮食生产的地区——加利福尼亚、澳大利亚、阿根廷无
        树大草原、欧洲西部等等——适合驯化的野动植物可能比新几内亚和美
        国东部还要少，因为在新几内亚和美国东部至少还出现了有限的粮食生
        产。
      - 在世界范围内对当地现有的大型哺乳动物的调查，都一致表明，所有这
        些不存在本地粮食生产或只有有限的本地粮食生产的地区，都缺少可驯
        化的牲畜和谷物的野生祖先。
      - 粮食生产的出现涉及粮食生产与狩猎采集之间的竞争问题。
        - 因此，人们也许想要知道，粮食生产出现缓慢或没有出现粮食生产这
          种种情况，可能是由于当地可以猎取和采集的资源特别丰富，而不是
          由于适合驯化的物种特别容易获得。
        - 事实上，当地粮食生产出现很晚或根本没有出现粮食生产的大多数地
          区，向狩猎采集族群所提供的资源持别贫乏而不是特别丰富，因为澳
          大利亚和美洲(而不是欧亚太陆和非洲)的大多数大型哺乳动物，到冰
          期快结束时已经灭绝。粮食生产所面临的来自狩猎采集的竞争．在这
          些地区甚至比在新月沃地少。因此，在当地未能出现粮食生产或粮食
          生产受到限制这些情况，决不能归咎于来自大量狩猎机会的竞争。
      - 印第安人未能驯化苹果的原因却是在于印第安人所能得到的整个野生动
        植物组合。这个组合的不太多的驯化潜力，就是北美粮食生产很晚才开
        始的主要原因

*** 九、 斑马、不幸的婚姻和安娜·卡列尼娜原则
    - 可驯化的动物都是可以驯化的；不可驯化的动物各有各的不可驯化之处。
    - 驯养的大型哺乳动物提供了肉食、奶制品、肥料、陆上运输、皮革、军事
      突击手段、犁具牵引、毛绒以及使先前没有抵抗力的民族失去生命的病菌。
    - 这14种古代大型食草类驯化哺乳动物的野生祖先，在地球上的分布是不均
      勾的。这样的野生祖先在南美只有一种，它产生了美洲驼和羊驼。北美、
      澳大利亚和非洲撒哈拉沙漠以南地区连1种都没有。非洲撒哈拉沙漠以南
      地区没有本地的驯化哺乳动物。相比之下，这14种中有13种(包括主要的5
      种中的全部)的野生祖先只有欧亚大陆（包括北非）才有。
    - 但大型哺乳动物的驯化实际上在4500年前就结束了。到那时，世界上全部
      148种可以用来驯化的候补大型动物必定已被试验过无数次，结果只有几
      种通过了试验，剩下的就再也没有适合驯化的了。
    - 相同的几种适于驯化的野生动物吸引了许多不同的人类社会的注意
    - 要能得到驯化，每一种候补的野生动物都必须具有许多不同的特点。缺少
      了哪一个必不可少的特点
      1. 日常食物
         - 每一次某种动物在吃某种植物或另一种动物时，食物生物量转换为取食者
           生物量的效率远远低于l0O％：通常在10％左右。由于这种根本性的缺乏
           效率，没有—种食肉的哺乳动物为了充当食物而被驯化
         - 即使在食草动物和杂食动物中，也有许多像树袋熊这样的动物在偏
           爱植物方面过分挑剔，要想成为饲养场里的牲畜实在不敢恭维。
         - 肉食动物
      2. 生长速度
         - 大猩猩和大象(15+)
      3. 圈养中的繁殖问题
         - 我们人类不喜欢在众目睽睽之下性交；有些具有潜在价值的动物也
           不喜欢这样傲
         - 猎豹和南美小羊驼
      4. 凶险的性情
         - 动则杀人的倾向使许多本来似乎理想的动物失去了驯化的候补资格
         - 8种野生的马科动物(马及其亲绕动物)在性情方而差异很大，虽然这
           8种在遗传上彼此非常接近，所以彼此可以交配并生出健康的(虽然
           通常不育的)后代。其中的两种——马和北非驴(现代驴的祖先)成功
           地得到驯化。
         - 非洲的4种斑马情况甚至更糟
         - 灰熊和、洲野牛、河马、中亚野驴、斑马、麋鹿和大角斑羚
      5. 容易受惊的倾向
         - 大多数鹿和羚羊((驯鹿是显著的例外)
      6. 群居结构
         - 几乎所有驯化的大型哺乳动物都证明它们的野生祖先具有3个共同的
           群居特点：它们生活在群体里；它们在群体成员中维持着一种完善
           的优势等级；这些群体占据重叠的生活范围，而不是相互排斥的领
           域。
         - 这种群居动物适合于放牧。既然它们彼此相安无事，所以就能把它
           们集中在一起。既然它们本能地跟随一个起支配作用的领袖．而且
           把人当作那个领袖而牢牢记住，所以它们就乐于接受牧人或牧羊狗
           的驱赶。群居动物在拥挤的圈养条件下也能生长良好，因为它们在
           野生时就已习惯于生活在密集的群体中了。
         - 猫和雪貂是唯一的得到驯化的地盘性哺乳动物，我们驯化它们的目
           的不是为了把它们当作肉食来源而大群地放牧，而是把它们当作独
           居的猎兽或宠物来饲养。
         - 地盘性动物，以下原因中只要有一个，它们中的大多数就不能驯化：
           1. 有许多动物的群体并不拥有重叠的生活范围，而是保持排斥其他
              群体的独占领域。
           2. 有许多动物在一年的部分时间里是群居的，到了交配季节就变成
              地盘性的了，这时它们见面就争斗，彼此不能相容。
           3. 许多群居动物．再一次包括大多数鹿和羚羊，并没有界限分明的
              优势等级，因此在本能上并没有准备把任何占支配地位的领袖牢
              记在心(因而也不会把人记在心上)
         - 人类同大多数动物缔结了一种不幸的婚姻，这是由于许多可能的原
           因中的一个或多个原因造成的：动物的日常食物、生长速度、交配
           习惯、性情、容易受惊的倾向以及群居组织的几个不同的特点。只
           有很少一部分野生哺乳动物由于在上述所有这些方面都能协调一致
           而最终得以和人类结成美满的婚姻。
         - 被传唤者众，而被选中者少

*** 十、 辽阔的天空和偏斜的轴线
    - 大陆轴线走向的差异所产生的巨大的、有时是悲剧性的后果。
    - 粮食生产的这种传播的主要路线，是从西南亚到欧洲、埃及和北非、埃塞
      俄比亚、中亚和印度河河谷；从萨赫勒地带和西非到东非和南非；从中国
      到热带东南亚、菲律宾、印度尼西亚、朝鲜和日本；以及从中美洲到北美
      洲。此外，粮食生产甚至在它的发源地由于来自其他发源地的另外一些作
      物、牲口和技术而变得更加丰富了。
    - 某种作物的迅速传播可能不但抢先阻止了同一植物的野生祖先在其他某个
      地方的驯化，而且也阻止了有亲缘关系的野生植物的驯化。
    - 粮食生产从西南亚向外传播的速度要比在美洲快，而且也可能比在非洲撒
      哈拉沙漠以南的地区快。这些现象包括：
      1. 粮食生产完全未能到达某些生态条件适合于粮食生产的地区；
      2. 粮食生产传播的速度和选择性方面存在着差异；
      3. 以及最早驯化的作物是否抢先阻止了对同一种植物的再次驯化或对近
         亲植物的驯化方面也存在着差异。
    - 大陆轴线走向的差异不仅影响粮食生产的传播，而且也影响其他技术和发
      明的传播。
    - 轮子和文字不像作物那样同纬度和白天长度有直接关系。相反，这种关系
      是间接的，主要是通过粮食生产系统及其影响来实现的。最早的轮子是用
      来运输农产品的牛拉大车的一部分。
    - 同美洲本地和撤哈拉沙漠以南非洲的农业传播速度相比，欧亚大陆农业的
      更快的传播速度在对欧亚大陆的文字、冶金、技术和帝国的更快传播方面
      发挥了作用。
** 第三部分 从粮食生产到枪炮、病茵与钢铁
*** 十一、 病菌的演化
*** 十二、 文字
    - 19世纪的作家往往把历史看作是从野蛮走向文明的进程。这一转变的主要
      标志，包括农业的发展、冶金、复杂的技术、集中统一的政府和文字
    - 知识带来力量。因此，文字也给现代社会带来了力量，用文字来传播知识
      可以做到更准确、更大量和更详尽，在地域上可以做到传播得更远，在时
      间上可以做到传播得更久。
    - 文字同武器、病菌和集中统一的行政组织并驾齐驱，成为一种现代征服手
      段。
    - 一头是“蓝图复制”，就是对现有的一幅详尽的蓝图进行复制或修改。另
      一头是“思想传播”，就是仅仅把基本思想接受过来，然后必须去重新创
      造细节。知道这能够做到，就会激励构你自己努力大干，但你最终的具体
      解决办法可能象也可能不象第一个发者的解决办法。
    - 文字只在新月沃地、墨西哥、可能还有中国独立出现，完全是因为这几个
      地方是粮食生产在它们各自的半球范围内出现的最早地区。一旦文字在这
      几个社会发明出来，它接着就通过贸易、征服和宗教向具有同样经济结构
      和政治组织的社会传播。
    - 大多数有文字的社会之所以获得文字，或是通过向邻近的社会借用，或是
      由于受到它们的启发而发明出文字，而不是靠自己独立创造出来的。
    - 相当多的发明都符合需要乃发明之母这个常识性的观点
*** 十三、 技术
    - 一旦发明了一种装置，发明者就得为它找到应用的地方。发明常常是需要
      之母，而不是相反。
    - 机动车是另一个在今天看来用途似乎显而易见的发明。然而，它不是为满
      足任何需求而发明出来的
    - 技术的发展是长期积累的，而不是靠孤立的英雄行为；技术在发明出来后
      大部分都得到了使用，而不是发明出来去满足某种预见到的需要。
    - 轮子、标名牛仔裤和标准打字机键盘说明了同一个社会对所有发明不是同
      样接受的不同原因
    - 对发明的接受
      1. 与现有效术相比较的相对经济利益。
      2. 社会价值和声望，这种考虑可以不顾经济利益(或没有经济利益)。
      3. 是否符合既得利益
      4. 新技术的优点能够很容易地看到
    - 社会之间在接受能力方面的差异是怎样产生的呢
      - 预期寿命变长了，这在原则上应能使未来的发明家不仅有耐心和有把握
         去制订长期的、延期得益的开发计划，而且也使他们可以有多年时间去
         积累技术知识。
      - 社会的经济和组织
        1. 古典时期可以得到廉价的奴隶劳动，这一点大概妨碍了当时的发明创
           造，而现在的高工资或劳动力短缺，对寻求技术解决办法起了刺激作
           用。
        2. 在现代的西方，保护发明者的所有权的专利权和其他财产法奖励发明．
        3. 现代工业社会提供了大量的技术培训的机会，这一点中世纪的伊斯兰教
           国家做到了，而现代的扎伊尔则没有做到。
        4. 和古罗马的经济不同，现代资本主义制度使投资技术开发有可能得到回
           报。
        5. 美国社会强烈的个人主义允许有成就的发明者为自己赚钱，而新几内亚
           牢固的家族关系则确保了一个人一旦开始赚钱就要同十几个指望搬来同
           吃同住的亲戚一起分享。
      - 解释是意识形态方面
        1. 为创新努力必不可少的冒险行为，在某些社会里比在另一些社会里
         普遍。
        2. 科学观点是文艺复兴后欧洲社会的独有特色，对于欧洲社会现代技
         术的卓越地位来说，这种特色确是功不可没。
        3. 对各种观点和异端观点的宽容促进了创新，而浓厚的传统观点(如中
         国强调中国古代的经典)则扼杀了创新。
        4. 宗教在其与技术创新的关系上差异很大：犹太教和基督教的某些教
         派据说与技术创新特别能够相容，而伊斯兰教、印度教和婆罗门教的某
         些教派可能与技术创新特别不能相容。
      - 其他影响因素，有时促进有时抑制
        - 战争、集中统一的政府、气候和丰富的资源
    - 有用的技术一旦获得，就必然会流传下去，直到有更好的技术来取而代之。
      技术不但必须获得，而且也必须予以保持
    - 如果没有技术的传播，得到的技术会更少，而丢失的现有技术会更多
    - 技术往往会催化自身
      1. 技术的进步决定于在这之前对一些比较简单的问题的掌握
      2. 新技术和新材料通过重新结合可以产生更新的技术
    - 第一次飞跃发生在10万年到5万年前，其所以能够发生，大概是由于我们
      身体的遗传变化，即人体的现代解剖学进化使现代语言或现代大脑功能或
      两者成为可能。这次飞跃产生了骨器、专用石器和复合工具。
    - 第二次飞跃来自我们选定的定居生活方式，这种生活方式在世界的不同地
      区发生的时间不同，在有些地区早在13000年前就发生了，在另一些地区
      即使在今天也还没有发生。就大多数情况而言，选定定居的生活方式是同
      我们采纳粮食生产联系在一起的，因为粮食生产要求我们留在我们的作物、
      果园和剩余粮食储备的近旁。
    - 最后，一个大陆上的每一个社会都体现了发展技术和采用技术的进一步机
      会，因为各个社会在创新精神方面由于许多不同的原因而存在着巨大的差
      异。因此，在所有其他条件相同的情况下，技术发展最快的是那些人口众
      多、有许多潜在的发明家和许多互相竞争的社会的广大而富有成果的地区。
    - 粮食生产开始的时间、技术传播的障碍和人口的多寡这3大因素的变化，
      是怎样直接导致我们所看到的各大陆之间在技术发展方而的差异的。
      1. 欧亚大陆(实际上也包括北非在内)是世界上最大的陆块，包含有数量
         最多的互相竞争的社会。它也是拥有粮食生产开始最早的两个中心的
         陆块，这两个中心就是新月沃地和中国。它的东西向的主轴线，使欧
         亚大陆一个地区采用的许多发明较快地传播到欧亚大陆具有相同纬度
         和气候的其他地区的社会。由于所有这些因素，后更新世技术的加速
         发展，在欧亚大陆开始得最早．从而导致了本地最大的技术积累。
      2. 美洲在地理和生态上却支离破碎：巴拿马地块宽不过40英里，等于在地理
        上把美洲腰斩了，就像这个地峡上的达里安雨林和墨西哥北部的沙漠在生
        态上所做的那样。墨西哥北部的沙漠把中美洲人类的先进社会向北美洲的
        社会分隔开了．而巴拿马地峡则把中美洲的先进社会同安第斯山脉地区和
        亚马孙河地区的社会分隔开了。此外，美洲的主轴线是南北走向，从而使
        大部分的技术传播不得不逆纬度(和气候)的梯度而行，而不是在同一纬度
        内发生。例如，轮子是在中美洲发明的，而美洲驼是不迟于公元前3000年
        在安第斯山脉中部驯化的，但过了5000年，美洲的这唯一的役畜和唯一的
        轮子仍然没有碰头，虽然中美洲马雅社会同印加帝国北部边界之间的距离
        (1200英里)比同样有轮子和马匹的法国同中国之间6000英里的距离要短得
        多
      3. 非洲撒哈拉沙漠以南地区是世界上第三大的陆块，但比美洲小得多。
         在人类的大部分历史中，到欧亚大陆比到美洲容易多了，但撒哈拉沙
         漠却仍然是一个主要的生态障碍，把非洲撒哈拉沙漠以南地区同欧亚
         大陆和北非隔开。非洲的南北轴线造成了欧亚大陆与非洲撤哈拉沙漠
         以南地区之间以及撒哈拉沙漠以南地区本身内部技术传播的又一障碍。
         作为后一障碍的例子，陶器和炼铁术出现在或到达非洲撒哈拉沙漠以
         南的萨赫勒地带(赤道以北)．至少同它们到达西欧一样早。然而，陶
         器直到公元元年才到达非洲的南端，而冶金术在从欧洲由海路到达非
         洲南端时，还不曾由陆路传播到那里。
      4. 澳大利亚是最小的一个大陆。澳大利亚大部分地区雨量稀少，物产贫
         乏，因此，就其所能养活的人口来说，它实际上就显然甚至更小。它
         也是一个最孤立的大陆。加之．粮食生产也从来没有在澳大利亚本地
         出现过。这些因素加在一起．就便澳大利亚成为唯一的在现代仍然没
         有金属制品的大陆。
    - 人口的差异是引人注目的：欧亚大陆(包括北非在内)的人口差不多是美洲
      人口的6倍，差不多是非洲人口的8倍，澳大利亚人口的230倍。
*** 十四、 粮食生产还使农民能够养活政治家(从平等主义到盗贼统治)
    - 其他许多以前从未与外界接触过的新几内亚人和亚马孙河地区印第安人的
      群体，同样由于传教士的作用而被吸收进现代社会。跟在传教士后面到来
      的是教师和医生、政府官员和士兵。政府和宗教的扩张在整个有文字记载
      的历史上一直就是这样相互联系在一起的，不管这种扩张是以和平手段实
      现的(如最后对法尤族人)．还是以暴力手段实现的。就后一种情况来说，
      通常都是由政府来组织征服，然后再由宗教来为这种征服辩护。虽然游牧
      民族和部落民族偶尔也打败过有组织的政府和宗教，但在过去的13000年
      中，总的趋势是：失败的还是游牧民族和部落民族。
    - 部落村庄里的家族是地位平等的氏族，而酋长管辖地的酋长家族的所有成
      员都享有世袭的特权
    - 酋长管辖地带来了对集中管理的、非平等主义社会来说带有根本性质的两
      难处境。从最好的方面说，它们可以提供个人无法承办的昂贵服务。从最
      坏的方面说，它们公然地在起着盗贼统治的作用，把实际财富从平民手中
      转移到上层阶级手中。这种高尚和自私的双重作用难分难解地联系在一
      起，虽然有些政府强调一种作用要大大多于强调另一种作用。盗贼统治者
      和英明政治家的区别，强盗贵族和公益赞助人的区别，只是程度不同而
      已：这只是一个从生产者那里榨取来的财物有多少被上层人物留下来的问
      题，是平民对把重新分配的财物用于公共目的喜欢到什么程度的问题。
    - 得不到公众支持的盗贼统治者有被推翻的危险，不是被受压迫的平民所推
      翻，就是被暴发的想要取而代之的盗贼统治者所推翻，这些新贵们用许诺
      为被窃取的果实提供更多服务的办法来谋求公众的支持。
    - 维持统治：
      1. 解除平民的武装，同时武装上层掌权人物。
      2. 用通行的方法把得到的财物的很大一部分再分配给群众来博取他们的
         欢心。
      3. 利用对武力的绝对控制来维持公共秩序和制止暴力以促进社会幸福
      4. 盗贼统治者为了得到公众支持而使用的最后一个方法，是制造一种为
         盗贼统治辩护的意识形态或宗教
         - 酋长声称，他为人民服务就是为他们向诸神说情和在仪式上吟诵为
           求得雨水、好年成和捕鱼成功所必需的咒语。
    - 有组织的宗教还为中央集权的社会带来了另外两个重大的好处
      1. 共同的意识形态或宗教有助于解决没有亲属关系的人们应如何共处而
         不致互相残杀这个问题——办法就是为他们规定一种不是以亲属关系
         为基础的约束
      2. 它使人们产生了一种为别人而牺牲自己生命的动机，而不是产生利己
         之心。以少数社会成员战死沙场为代价，整个社会就会在征服其他社
         会或抵御外侮时变得更加有效。
    - 我们今天最熟悉的政治、经济和社会制度就是国家制度
    - 城市与村庄的区别是城市有重要的公共工程，有统治者居住的宫殿，有来
      自贡物和税收的资本积累，还有粮食生产者以外的集中的人口
    - 早期的国家有一个资格相当于国王的世袭领袖．他很像一个超级的至高无
      上的酋长，对信息、决策和权力实行甚至更大的垄断。即使在今天的民主
      国家里，至关重要的知识也只有少数人能够获得，他们对信息流向政府的
      其余部门进行控制，结果也就是对决策进行控制
    - 粮食是由4个专业群体(生产谷物的农民、牧人、渔民以及果园和菜园的种
      植者)生产的，国家从每一个群体那里得到产品，又向每一个群体分配必
      需的日常用品、工具和这个集团所不生产的食物。国家向种植谷物的农民
      供应种子和耕畜，从牧人那里得到羊毛，通过远方贸易用羊毛交换金属制
      品和其他必不可少的原料，并向维护农民所依赖的灌溉系统的劳动者发放
      粮食。
    - 为了解决国家内部的冲突，法律、法制和警察机关越来越正规化了
    - 早期的国家已有了国家的宗教和标准化的寺庙。美索不达米亚的寺庙不但
      是宗教活动的中心，而且也是经济再分配、文字和手工技术的中心。
    - 这方面最根本的差别是，国家是按政治和领土而组建起来．不是按照划分
      族群、部落和简单的酋长管辖地的亲属关系而组建起来的。
    - 国家在与较简单的实体发生冲突时所以能取得胜利，部分原因是国家拥有
      武器和其他技术方面的优势，同时也拥有人口数量上的优势。但酋长管辖
      地和国家还有另外两个固有的潜在优势。首先，中央决策者拥有集中军队
      和资源的优势。其次，许多国家的官方宗教和爱国热忱使它们的军队在作
      战中视死如归，心甘情愿地为国捐躯。
    - 在现代国家中，乐于为国牺牲的思想由我们的学校、教会和政府大力灌输
      给我们公民．使我们忘记了它标志着同以往人类历史的彻底决裂。
    - 地区人口的多少是预测社会复杂程度的最有力的唯一根据
    - 众多的或稠密的人口只有在粮食生产的条件下，或至少对狩猎采集来说物
      产特别丰富的条件下才会产生。有些物产丰富的狩猎采集社会已达到了可
      以组织酋长管辖地的水平，但还没有一个达到国家的水平，因为所有国家
      都要靠粮食生产来养活它们的国民。
    - 集约化的粮食生产和社会的复杂程度通过自我催化而相互促进
    - 只有复杂的中央集权的社会才能组织公共工程(包括灌溉系统)、远距离贸
      易(包括输入金属以制造更好的农具)和各种经济专门团体的活动(如用农
      民的粮食养活牧人，又把牧人的牲口提供给农民作耕畜之用)。中央集权社
      会的所有这些功能，促进了集约化的粮食生产，从而也促进了整个历史上
      的人口增长。
    - 粮食生产至少在3个方而帮助复杂的社会形成了鲜明的特点：
      1. 它随季节变化定期地投入劳动力。
         - 收成贮藏好之后，中央集权的行政机构就可以利用农民的劳动力来
           兴建宣扬国威的公共工程(如埃及的金字塔)，或兴建可以养活更多
           人口的公共工程(如波利尼西亚群岛中夏威夷的灌溉系统或鱼塘)，
           或从事扩大政治实体的征服战争。
      2. 组织粮食生产以产生余粮储备，从而使经济专门化和社会层次化成为
         可能。
      3. 粮食生产促使人们或要求人们采取定居的生活方式，这种生活方式是
         积累足够的财产、发展复杂技术和精巧手艺以及兴建公共工程的一个
         先决条件。
    - 传教士和官员的目的：
      - 一个目的当然就是“安抚”这些游牧部落的显而易见的目的；即说服他
        们不要杀害传教士和官员，也不要自相残杀。
      - 另一个目的就是劝诱这些游牧部落在村庄里定居下来，这样传教士和官
        员就能找到他们，给他们带来医疗保健和学校教育之类的服务，并使他
        们改变宗教信仰从而控制他们。
      - 对解决冲突、决策、经济因素和空间的这些考虑，于是综合起来要求大
        型社会实行中央集权，但权力的集中不可避免地为那些掌权的人、私下
        据有信息的人、作决定的人和对财货进行再分配的人大开方便之门，使
        他们得以利用由此带来的机会为他们自己和他们的亲属谋取好处
    - 合并的发生不外乎下面的两种方式之一：在外力的威胁下合并，或通过实
      际的征服
      - 在外力威胁下实现合并的很好的例子，是美国东南部切罗基族印第安同
        盟的组成
      - 通过征服而实现的例子，非洲东南部祖鲁国的起源
    - 战败民族的命运取决于人口的密度：
      - 凡是人口密度很低的地方，就像在狩猎采集族群占据的地区所常见的那
        样，战败群体的幸存者只要离开他们的敌人远一点就行了。新几内亚和
        亚马孙河地区游牧部族之间战争的结果往往就是这样。
      - 凡是人口密度中等的地方，就像粮食生产部落占据的地区那样，没有大
        片空旷的地方可以让战败族群的幸存者逃避。但是，没有集约型粮食生
        产的部落社会不使用奴隶，也不能生产出可以作为很大一部分贡品的足
        够的剩余粮食。因此，战败部落的幸存者对胜利者来说毫无用途，除非
        娶他们的女人为妻。战败的男人都被杀死了，他们的地盘也可能为胜利
        者所占有。
      - 凡是人口密度高的地方，就像国家或酋长管辖地所占有地区那样，被打
        败的人仍然无处可逃，但胜利者不杀死他们而有了利用他们的两种选择。
        由于酋长管辖地社会和国家社会已出现了经济专业化，被打败的人可以
        当奴隶来使用，就像在(圣经)时代通常发生的那样。或者，由于许多这
        样的社会已经有了能够生产大量剩余粮食的集约型粮食生产系统，胜利
        者可以让战败者仍然从事原来的劳作，只是剥夺了他们的政治自主权，
        要他们定期地用粮食或货物来纳贡．并把他们的社会合并入获胜的国家
        或酋长管辖地。
    - 因此，粮食生产及社会之间的竞争与混合，产生了征服的直接原动力：病
      菌、文字、技术和中央集权的政治组织。这些都是终极原因，是通过因果
      关系链而表现出来的，虽然这些因果关系在细节上有所不同，但全都与稠
      密的庞大人口和定居的生活方式有关。不过这种联系并不是绝对的
    - 澳大利亚是唯一的这样的大陆：那里的各个土著族群在现代的生活中仍然
      没有所谓文明的任何特征——没有农业，没有畜牧业，没有金属，没有弓
      箭，没有坚固的房屋，没有定居的村庄，没有文字，没有酋长管辖地，也
      没有国家

** 第四部分 在5章中环游世界
*** 十五、 澳大利亚
    - 澳大利亚粮食生产的发展必须等待非本地作物和牲口的引进，这些作物和
      牲口是在世界上气候相似的地区驯化的，而这些地方过于遥远，如果没有
      越洋船只的运输，那里的驯化动植物是到不了澳大利亚的。
    - 在澳大利亚创造社会的人是澳大利亚的土著。当然，他们所创造的社会不
      是一个有文字的、从事农业生产的工业民主的社会。其原因是由澳大利亚
      的环境特点直接造成的。
*** 十六、 东亚大陆和太平洋诸岛，迁移及冲突
    - 中国在粮食生产、技术、文字和国家组成方而的领先优势所产生的结果
      是，中国的创新改革对邻近地区的发展也作出了重大的贡献。
    - 中国的这种影响就像蒸汽压路机—样势不可挡，先前的热带东南亚民族在
      这一地区的现代居民中几乎没有留下任何痕迹。只剩下狩猎采集族群的3
      个孑遗群体——马来半岛的塞芒族矮小黑人、安达曼群岛岛民和斯里兰卡
      维多依族矮小黑人——使我们想到热带东南亚的原先居民可能是黑肤、卷
      发，就像现代的新几内亚人，而不像肤色较浅、直发的中国华南人及其旁
      系亲属现代的热带东南亚人
    - 中国的华南人发展了本地的粮食生产和技术，接受了华北的文字、更多的
      技术和政治组织，又进而向热带东南亚和台湾移民，大规模地取代了这些
      地区的原有居民。在东南亚，在那些从事粮食生产的华南移民的后代或亲
      戚中，在泰国东北部和老挝山区雨林中的永布里人重新回到狩猎采集生
      活，而永布里人的近亲越南人(所说的语言和永布里语言同属南亚语的一
      个语支)始终是肥沃的红河三角洲的粮食生产者，并建立了一个广大的以
      金属为基础的帝国。同样，在说南岛语的来自台湾和印度尼西亚的农民移
      民中，婆罗洲雨林中的普南人被迫回到了狩猎采集的生活方式，而他们的
      生活在肥沃的爪哇火山土上的亲戚们仍然是粮食生产者，在印度的影响下
      建立了一个王国，采用文字，并在婆罗浮屠建有巨大的佛教纪念性建筑物。
      这些进而向波利尼西亚移民的南岛人同东亚的冶金术和文字隔绝了，因此
      始终没有文字，也没有金属。
    - 与澳大利亚和美洲不同，东亚和大多数太平洋岛屿仍然为东亚民族和太平
      洋民族所占有。
*** 十七、 旧大陆社会之间新近的碰撞
    - 在美洲广大地区唯一缺少的为进行粮食生产所需要的成分是家畜和作物本
      身
    - 不利条件：广泛依赖蛋白质含量低的玉米，而不是欧亚大陆的品种繁多、
      蛋白质丰富的谷物；种子用手一颗颗地点种，而不是撒播；犁地用手而不
      是用畜力，用畜力犁地使一个人能够耕种大得多的而积，并可耕种某些难
      以用手耕种的肥沃而坚硬的土壤和长满草根的土地(就像北美大平原的那
      些土地)；缺乏可以增加土壤肥力的动物粪肥；只用人力而不是用畜力来
      做诸如脱粒、碾磨和灌溉之类的农活。
    - 这些差距归根到底是由于欧亚大陆有历史悠久得多的依靠粮食生产的人口
      稠密、经济专业化、政治集中统一、相互作用、相互竞争的社会。有5个
      技术领域可以挑出来讨论：
      1. 金属——开始时是铜，后来是青铜，最后是铁——到1492年止已在所
         有复杂的欧亚大陆社会被用作工具。相比之下，虽然铜、银、金和一
         些合金已在安第斯山脉地区和美洲的其他一些地方被用作饰物，但石
         头、木头和骨头在所有印第安社会中仍然是制作工具的主要材料，这
         些社会只在局部地区有限地利用铜器。
      2. 欧亚大陆的军事技术比美洲的军事技术要有效能得多，印第安军队没
         有任何可以与马匹相抗衡的牲口
      3. 欧亚大陆社会在利用动力源运转机械方面拥有巨大的优势。超越人力
         的最早进展是利用动物——牛、马和驴——来拉犁就地和转动轮子来
         磨谷、提水、灌溉或排水。水轮在罗马时代就已出现了，后来到了中
         世纪数量日渐增多，这时又出现了潮汐磨机和风车。
      4. 轮子早己成为欧亚大陆大部分陆上运输的基础
      5. 海上运输。许多欧亚大陆社会发明了大型帆船，其中有些能逆风航行
         并能横渡大洋，船上装备有六分仪、磁罗盘、尾柱舵和大炮。无论在
         装载量、速度、机动性或是抗风浪能力方面，欧亚大陆的这些船只都
         比新大陆最先进的社会即安第斯山脉地区和中美洲的社会用来进行贸
         易的那些木筏优越得多。
    - 除了在病菌和技术方面的差异外，欧亚大陆社会和印第安社会在政治组织
      方面也存在着差异。
    - 其中的哈布斯堡王朝、奥斯曼帝国、中国的历代国家、印度的莫卧儿帝国
      和13世纪达到全盛时期的蒙古帝国，一开始就是通过征服其他国家而形成
      的多种语言的民族大融合。许多欧亚大陆国家和帝国都有官方的宗教，用
      以加强国家的凝聚力，使政治领导合法化和批准对其他民族的战争。
    - 大多数欧亚大陆国家都有由有文化的人组成的行政机构，在某些国家里，
      官员以外的平民大众中也有相当一部分人是有文化的。文字使欧洲社会得
      到行政管理和经济交换之便，激励与指导探险和征服，并可利用远方和古
      代的一系列信息和人类经验。相比之下，在美洲．文字只在中美洲很小的
      一个地区内的上层人士中使用。印加帝国使用了一种以结绳(叫做基普)为
      基础的会计制度和记忆符号，但作为一种传递详细信息的手段，它还不可
      能起到文字的作用。
    - 起步晚，可用于驯化的野生动植物系列比较有限，较大的传播障碍，以及
      稠密的人口在美洲生活的地区可能比在欧亚大陆小，或者可能比在欧亚大
      陆孤立。

*** 十八、 欧洲民族和美洲印第安人之间的冲突
    - 在适合欧洲的粮食生产和欧洲人生理机能的气候最温和的地区，人口众多
      的印第安社会被消灭了。在北美洲，相当大的保存下来的完整社会，现在
      多半生活在居留地里或其他一些被认为不适于欧洲的粮食生产和采矿的地
      方，如北极地区和美国西部的贫瘠地区。许多热带地区的印第安人已被来
      自旧大陆热带地区的移民所取代(尤其是非洲黑人以及亚洲的印度人和苏
      里南的爪哇人
*** 十九、 非洲撒哈拉沙漠以南地区的历史
    - 欧洲民族和非洲民族本身之间的差异有关。是由于地理学和生物地理学的
      偶然因素所致——特别是由于这两个大陆之间不同的面积、不同的轴线方
      向和不同的动植物品种所致。就是说，非洲和欧洲的不同历史发展轨迹归
      根到底来自它们之间的“不动产”的差异。
*** 十九、 总结
    - 各大陆的环境有无数的不同特点，正是这些不同的特点影响了人类社会的
      发展轨迹。只有4组差异是最重要的
      1. 各大陆在可以用作驯化的起始物种的野生动植物品种方面的差异
      2. 那些影响传播和迁移速度的因素．而这种速度在大陆与大陆之间差异
         很大。大陆的主轴线和地理与生态障碍
      3. 影响大陆之间传播的因素
      4. 各大陆之间在面积和人口总数方面的差异
    - 为什么新月沃地和中国把它们几千年的巨大的领先优势最后让给了起步晚
      的欧洲。当然，人们可以指出促使欧洲兴起的一些直接因素：它的商人阶
      级、资本主义和对发明的专利保护的逐步形成，它的未能产生专制独裁的
      君主和使人不堪重负的税收，以及它的希腊—犹太教—基督教的批判经验
      主义调查研究的传统。不过，对于所有这些直接原因，人们一定会提出关
      于终极原因的问题：为什么这些直接因素出现在欧洲，而不是出现在中国
      或新月沃地?
    - 新月沃地由于当地集中了可以驯化的动植物而拥有了领先优势。如果它一
      旦失去了这种优势，它就不再有任何引人注目的地理优势可言
    - 过去的新月沃地的广大地区现在成了沙漠、半沙漠、干草原和不适合农业
      的受到严重侵蚀或盐碱地的土地。这个地区的某些国家的短暂财富是建立
      在单一的不能再生的石油资源的基础上的，这一现象掩盖了这个地区的长
      期贫困和难以养活自己的情况。
    - 新月沃地和东地中海社会不幸在一个生态脆弱的环境中兴起。它们破坏了
      自己的资源基础，无异于生态自杀
    - 从东方(新月沃地)最古老的社会开始，每一个东地中海社会都在轮流地自
      挖墙脚，而就在这个过程中，权力西移了。欧洲北部和西部没有遭到同样
      的命运，这不是因为那里的居民比较明智，而是因为他们运气好，碰巧生
      活在一个雨量充沛、植被再生迅速的好环境里。
    - 欧洲是从新月沃地得到它的作物、牲畜、技术和书写系统的，而新月沃地
      后来反而使自己失去了作为一个主要的权力和发明中心的地位
    - 中国一长串重大的技术第一包括铸铁、罗盘、火药、纸、印刷术以及前面
      提到过的其他许多发明。它在政治权力、航海和海上管制方面也曾在世界
      上领先。
    - 事实上．正是由于欧洲是分裂的，哥伦布才成功地第五次在几百个王公贵
      族中说服一个来赞助他的航海事业。一旦西班牙这样开始了欧洲对美洲的
      殖民，其他的欧洲国家看到财富滚滚流人西班牙，立刻又有6个欧洲国家
      加入了对美洲殖民的行列。对于欧洲的大炮、电灯照明、印刷术、小型火
      器和无数的其他发明，情况也是如此：每一项发明在欧洲的一些地方由于
      人们的习性起先或者被人忽视．或者遭人反对，但一旦某个地区采用了
      它，它最后总能传播到欧洲的其余地区。
    - 欧洲分裂所产生的这些结果与中国统一所产生的结果形成了鲜明的对比。
      中国的经常统一与欧洲的永久分裂都由来巳久。中国自有文字以来就一直
      只有一种书写系统，长期以来只有一种占支配地位的语言，以及2000年来
      牢固的文化统一。欧洲内部的分歧今天在继续挫败甚至是想要通过欧洲经
      济共同体来实现欧洲统一的并不过分的企图，这就表明欧洲对分裂的根探
      蒂固的执着。
    - 因此，了解了中国把政治和技术的卓越地位让给欧洲这方面的真正问题，
      就是了解了中国的长期统一和欧洲的长期分裂的问题
    - 欧洲海岸线犬牙交措，它有5大半岛，每个半岛都近似孤悬海中的海岛，
      在所有这些半岛上形成了独立的语言、种族和政府；希腊、意大利、伊比
      利亚半岛、丹麦和挪威/瑞典。中国的海岸线则平直很多，只有附近的朝
      鲜半岛才获得了作为单独岛屿的重要性。欧洲有两个岛(大不列颠岛和爱
      尔兰岛)，它们的面积都相当大，足以维护自己的政治独立和保持自己的
      语言和种族特点，其中的一个岛(大不列额岛)因为面积大，离欧洲大陆又
      近，所以成了一个重要的欧洲独立强国。但即使是中国的两个最大的
      岛——台湾岛和海南岛，面积都不到爱尔兰岛的一半，这两个岛都不是重
      要独立的政体；而日本在地理上的孤立地位使它在现代以前一直处于与亚
      洲大陆的政治隔绝状态，其程度远远超过了大不列颠与欧洲大陆的政治隔
      绝状态。欧洲被一些高山(阿尔卑斯山脉、比利牛斯山脉、喀尔巴阡山脉
      和挪威边界山脉)分割成一些独立的语言、种族和政治单位，而中国在西
      藏高原以东的山脉则不是那样难以克服的障碍。中国的中心地带从东到西
      被肥沃的冲积河谷中两条可通航的水系(长江和黄河)连接了起来，从南到
      北又由于这两大水系(最后有运河连接)之间比较方便的车船联运而成为一
      体。因此，中国很早就受到了地域广阔的两个高生产力核心地区的决定性
      影响，而这两个地区本来彼此只有微不足道的阻隔，后来竞合并为一个中
      心。欧洲的两条最大的河流——莱茵河与多瑙河则比较小，在欧洲流经的
      地方也少得多。与中国不同，欧洲有许多分散的小的核心地区，没有一个
      大到足以对其他核心地区产生长期的决定性影响，而每一个地区又都是历
      史上一些独立国家的中心。
    - 中国一旦于公元前221年最后获得统一，就再没有任何其他的独立国家有
      可能在中国出现并长期存在下去。虽然在公元前221年后有几个时期出现
      了分裂局面，但最后总是重新归于统一。但欧洲的统一就连查理曼、拿破
      仑和希特勒这些下定决心的征服者都无能为力；甚至罗马帝国在其鼎盛时
      期所控制的地区也没有超过欧洲的一半。
    - 但中国在地理上的四通八达最后却成了一个不利条件，某个专制君主的一
      个决定就能使改革创新半途而废，而且不止一次地这样做了。相比之下，
      欧洲在地理上的分割形成了几十个或几百个独立的、相互竞争的小国和发
      明创造的中心。如果某个国家没有去追求某种改革创新，另一个国家会去
      那样做的，从而迫使邻国也这样去做，否则就会被征服或在经济上处于落
      后地位。欧洲的地理障碍足以妨碍政治上的统一，但还不足以使技术和思
      想的传播停止下来。欧洲还从来没有哪一个专制君王能够像在中国那样切
      断整个欧洲的创造源泉。
    - 环境因素不但与历史的最广泛模式有关，而且也与较小规模和较短时期的
      历史模式有关。
    - 新月沃地和中国的历史还为现代世界留下了一个有益的教训：环境改变
      了，过去是第一并不能保证将来也是第一。人们甚至会怀疑，本书从头到
      尾所运用的地理学推论在现代世界上是否终于变得毫不相干，因为思想可
      以在因特网上立即向四处传播，而货物照例可以一下子从一个洲空运到另
      一个洲。看来，对全世界各民族之间的竞争己实行了一些全新的规则，结
      果，像朝鲜、马来西亚，尤其是日本这些新的力量出现了。
    - 世界上两个最早的粮食生产中心——新月沃地和中国仍然支配着现代世
      界，或者是通过它们的一脉相承的国家(现代中国)，或者是通过位于很早
      就受到这两个中心影响的邻近地区内的一些国家(日本、朝鲜、马来西亚
      和欧洲)，或者是通过由它们的海外移民重新殖民或统治的那些国家(美国、
      澳大利亚、巴西)。撒哈拉沙漠以南的非洲人、澳大利亚土著和美洲印第
      安人支配世界的前景仍然显得黯淡无光。
    - 一个极端是历史学家托马斯·卡莱尔的观点：“世界的历史就是人[原文
      如此]在这个世界上所取得的成就的历史，实际上就是在这个世界上活动
      的伟人的历史。
    - 从研究历史中去获得普遍原则，要比从研究行星轨道中去获得普遍原则来
      得困难。
    - 物理学家和化学家能够在宏观的层次上系统地阐述带有普遍性的决定论的
      规律，但生物学家和历史学家只能系统地阐述统计学上的趋势。
    - 这些领域的每一个领域都在不同程度上受到以下几个方面的因扰：不可能
      进行可复制的对照实验的介入，大量变数带来的复杂性，每一个系统因而
      变得独一无二，结果不可能系统地阐述普遍的规律，以及难以预测突现性
      质和未来变化。

* [[file:index.html][wiki]]
