# -*- org -*-
# -*- coding:utf-8 -*-

# Time-stamp: <2016-07-23 14:32:44 (mykulou@gmail.com)>
#+SETUPFILE: theme-bigblow-local.setup

* 追寻生命的意义
   - 每一时刻的各种经历都是短暂的，但发生过就被保存下来，也永恒地存在。
   - 存在的短暂性，让人必须做出选择， 要为了什么，对什么人或什么事负责。
   - 不能去寻找抽象的意义，生命中的每一种情境向人提出挑战，同时提出疑
     难要他去解决，每一个人都被生命询问，而他只有用自己的生命才能回答
     此问题；只有以“负责”来答复生命。
   - 因为人类的存在，本质上是要"自我超越"(Self-transcendence)而非自我
     实现(Self-actualization)。 一个人为实践其生命意义而投注了多少心
     血，他就会有多少程度的自我实现
   - 自我超越就是发展，进步，是过程；"自我实现"只是当"自我超越"之后的
     副产品而已。
   - 发现意义的途径：创造、工作；体认价值；受苦。
   - 改变自己别人的生活，为发展进步做贡献
   - 打针的痛苦
   - 明确与目标的差距，就是当前可进步的空间

** 存在的空虚
   - "存在的空虚"是二十世纪的一种普遍现象。这是可以理解的，因为人类
     要成为真正的"人"时，必须经历双重的失落，由此而产生存在的空虚。
   - 本能冲动不告诉他应该作什么；传统也不告诉他必须作什么，很快地他
     就不知道自己要作什么了，于是他愈来愈听从别人要他去作什么，于是
     他就愈来愈成为顺从主义的牺牲者了。
   - 叔本华所说的，"人类注定永远在两极之间游移：不是灾难疾病，就是无
     聊厌烦。"事实上，现时代中所兴起的无聊厌烦感，比起灾难疾病要给精
     神科医师带来更多的问题。
   - 此外，还有许多种不同的面具及伪装隐藏着存在的空虚。有时求意义的
     意志受到挫折，于是用其他代替者作为朴偿，例如求权力的意志(包括最
     原始型态的权力意志)以及求金钱的意志。也有些时候．这种受挫的求意
     义意志被求享乐的意志所取代，因此成为性的代偿作用(compensation)。
     在这些案例身上我们可以看到，因为存在的空虚，性欲遂猖獗泛滥。
   - 用概括性的措辞来回答这问题，正如我们去问一位下棋圣手说："大师，
     请告诉我在这世界上最好的一步棋如何下法?"根本没有所谓最好的一步
     棋，甚至也没有不错的一步棋，而要看弈局中某一特殊局势，以及对手
     的人格型态而定。
   - 一个人不能去寻找抽象的生命意义，每个人都有他自己的特殊天职或使
     命，而此使命是需要具体地去实现的
   - 生命中的每一种情境向人提出挑战，同时提出疑难要他去解决，因此生
     命意义的问题事实上应该颠倒过来。人不应该去问他的生命意义是什么。
     他必须要认清，“他”才是被询问的人。一言以蔽之，每一个人都被生
     命询问，而他只有用自己的生命才能回答此问题；只有以“负责”来答
     复生命。因此，意义治疗学认为“能够负责”(Responsibleness)是人类
     存在最重要的本质。
** 存在的本质
   - 意义治疗法企图使病人深深体会到他自己的责任，因此必须让他自由抉择
     为了什么，对什么人或什么事负责。他了解是他自己要负责。
   - 因此，病人必须自行决定他究竟该对社会负责，抑或对良知负责。不过，
     也有不少人自认为该对上苍，对天主负责。他们不只以承担责任的角度，
     更以承行上天旨意的角度来诠释自己的生命。
   - 人是一种能够负责的物种，他必须实现他潜在的生命意义。我这样说，是
     希望强调：生命的真谛，必须在世界中找寻，而非在人身上或内在精神中
     找寻，因为它不是个封闭的体系。同样地，我们无法在所谓的"自我实现"
     上找到人类存在的真正目标；因为人类的存在，本质上是要"自我超越
     "(Self-transcendence)而非自我实现(Self-actualization)。 一个人为
     实践其生命意义而投注了多少心血，他就会有多少程度的自我实现。换言
     之，"自我实现"如果作为目的，是永不能获得的，它只是当"自我超越"之
     后的副产品而已。
   - 我们已经指出了生命的意义是会改变的，但永远不失其为意义，按照意义
     治疗学，我们能以三种不同的途径去发现这意义：
     1. 创造、工作。
     2. 体认价值。
     3. 受苦。
   - 具体
     1. 第一种，显然是功绩或成就之路。
     2. 第二种途径是经由体验某种事物，如工作的本质或文化；或经由体验某
        个人，如爱情，来发现生命的意义。
        - 爱是进入另一个人最深人格核心之内的唯一方法。没有一个人能完全
          了解另一个人的本质精髓，除非爱他。借着心灵的爱情，我们才能看
          到所爱者的真髓特性。
     3. 生命的意义是绝对的，它甚至包括潜伏的痛苦的意义。
        - 问题是有一种猿类很容易发生脊髓灰白质炎，因此必须时常给它打
          针，那么它是否可以了解其所受痛苦的意义?全体一致回答它当然不
          能了解，因为它有限的智能是无法进入人类世界的，而人类是唯一能
          了解痛苦的意义。
** 超越的意义
   - 使得人生看起来没有意义的事，除痛苦之外还有濒死；除疾病之外，还有
     死亡。但是我愿意强调，生命中唯一真正短暂无常的部分是它的潜在力，
     这些潜力一旦成为事实，立刻就变成过去。然而，凡存在过的，会永恒地
     存在，因此它们就从短暂性中被解救及被保存起来。
   - 如此说来，我们存在的短暂性决不会是没有意义的，反而构成了我们的责
     任感。因为每样事物的关键点就在于我们知道它是短暂的，所以人必须不
     断地抉择，哪些要做，哪些不要做，何种抉择可成为一种不朽的生命痕迹?
     在任何时刻，人都要决定(不管是因而变得更好或是更坏)什么样的事物，
     将成为他存在的里程碑。
* [[file:index.html][wiki]]
